### ISSUE TITLE
Change or revision request in cave generation 1.20.1 - v2.2.1

### ISSUE THREAD

**Issue by Minato245** [Apollounknowndev/tectonic#101]
Because it is not found in the public discord link by this means.

In the worlds I have generated, in the deepest layer a fairly giant type of cave is always generated from approximately height -42 to -58, usually with a river of lava. It is quite frequent and absurdly long, reaching more than 10,000 blocks. I don't know if it was made with that intention, however, it would be nice if it wasn't so frequent or so long. Like underground river caves, there are some that are absurdly long and at some point lose the "river" shape (although they are rare).

I am just a simple mod user so I have no idea if it can be solved, I am just giving my opinion and I hope it is taken into account, thank you very much and it is a good mod.

Here are some images of what I mean, the fov is at maximum so that more field can be seen.

![2024-03-13_13 50 59](https://github.com/Apollounknowndev/tectonic/assets/67383031/9c30fc71-c1b2-4d5a-838f-9eaa767af8b4)
![2024-03-13_14 06 29](https://github.com/Apollounknowndev/tectonic/assets/67383031/970f2218-db9c-4186-8e7e-78a925328cde)

**Comment by Apollounknowndev** [comment]
Underground rivers (both lava and water) are intended, and due to the way that the world generation system works they have no minimum or maximum size. These will be toggleable in a future update.
