### ISSUE TITLE
Added compatibility with William Wythers' Expanded Ecosphere

### ISSUE THREAD

**Issue by hanweiyyds** [Apollounknowndev/tectonic#104]
Hello, I would like to make the new terrain added by WWEE generate properly in the Tectonic world, can you be compatible with WWEE?

**Comment by Apollounknowndev** [comment]
WWEE is a discontinued mod and it already works with Tectonic if you enable it's compatibility mod, so no.

**Comment by lawrencedumarey** [comment]
How to enable compatibility mode?
