### ISSUE TITLE
Error with Tectonic and Terralith forge 1.18.2

### ISSUE THREAD

**Issue by oRadiatorExtrem** [Apollounknowndev/tectonic#105]
### The server crashes when I add Tectonic to my modpack wich has Terralith. My server is in forge 1.18.2 40.24.
I will leave both the debug.log and the latest.log down here

**debug:**
https://mclo.gs/lBsVjJX

**latest:**
https://mclo.gs/mErdw48

**The Terralith version is 1.18.2 v2.2.6**

**The Tectonic version is 1.18.2 v2.2.1**

**Comment by Apollounknowndev** [comment]
Fixed in v2.2.1a.
