### ISSUE TITLE
How can i change how large a Biome is? and how can i do that the Oceans are not that deep but deep and the Oceans smaller

### ISSUE THREAD

**Issue by tillbaxmann** [Apollounknowndev/tectonic#107]
Can you name the Files and the Parameters that i have to change, that i can make the Biomes smaller, and the oceans not that deep and the oceans smaller

**Comment by samuelbarrett** [comment]
This mod (and the accompanying [Lithostitched mod](https://github.com/Apollounknowndev/lithostitched/) by the same author are in need of some explanatory documentation. I'm in the process of working it out, but if anyone can link to existing docs that would be much appreciated!

**Comment by Apollounknowndev** [comment]
> This mod and the accompanying [Lithostitched mod](https://github.com/Apollounknowndev/lithostitched/) by the same author are in need of some explanatory documentation. I'm in the process of working it out, but if anyone can link to existing docs that would be much appreciated!

Lithostitched has a wiki [here](https://github.com/Apollounknowndev/lithostitched/wiki) explaining everything in the mod. Tectonic will not be getting documentation as the backend is quite a mess. A config is being considered, though.

**Comment by Apollounknowndev** [comment]
> Can you name the Files and the Parameters that i have to change, that i can make the Biomes smaller, and the oceans not that deep and the oceans smaller

Making biomes smaller in Tectonic is done in the same way you'd make biomes smaller in vanilla. I'd highly recommend asking in a server like [Stardust Labs](https://discord.gg/stardustlabs) where you can get guidance on modifying biome size + parts of the Tectonic pack much more efficiently than through Github.
