### ISSUE TITLE
Biome generation being overwritten by tectonic

### ISSUE THREAD

**Issue by Masonono** [Apollounknowndev/tectonic#108]
I looked at the issues posted here before posting this and belive the issue is sill present I have a myriad of world gen mods and have tried everything spare altering the mods manually the generation works fine with all mods installed but when tectonic is activated this happens 
![image](https://github.com/Apollounknowndev/tectonic/assets/75645752/1365074c-7bfb-4142-a542-ffbca6f6c93b)
sorry if im being ignorant by posting this I really want this to work
the mod list is chunky and I tried to order them to try to get them to work together (the suffixes) any help or input is appreciated!

**Comment by Masonono** [comment]
I never posted the mod list. My bad
![image](https://github.com/Apollounknowndev/tectonic/assets/75645752/00b47c8d-9d10-46b1-88bf-98309ed563d3)

**Comment by Apollounknowndev** [comment]
Issue with WWOO, nothing I can do about it.

**Comment by Masonono** [comment]
thanks!
