### ISSUE TITLE
[Fabric] [1.20.1] Ocean monuments do not generate lower to compensate for Tectonic deeper oceans

### ISSUE THREAD

**Issue by AncletYinglet** [Apollounknowndev/tectonic#109]
See attached image:

![image](https://github.com/Apollounknowndev/tectonic/assets/148595378/f960b544-7f03-4861-baf9-9e1c4317f1da)
Seed: 5845507104842247104
XYZ: -676/47/666

I don't believe this is a _bug_ per se, rather perhaps unintentional structure gen. It is also somewhat odd looking as well. I'm curious if this will be looked into (or can be looked into), if only for the sake of aesthetics/consistency. Shipwrecks, ocean ruins, underwater nether portals, etc. tend to generate as intended (i.e. on the bottom of the ocean floor) in similar situations (see other attached pictures), ocean monuments do not however.

![image](https://github.com/Apollounknowndev/tectonic/assets/148595378/691796ab-17f3-473e-abda-2f6ba750e60e)
![image](https://github.com/Apollounknowndev/tectonic/assets/148595378/49954d2d-838d-475b-8042-3cc9caa44251)

Same results achievable on fresh 1.20.1 install with only Tectonic installed, no other mods.

**Comment by Apollounknowndev** [comment]
Unfixable in the datapack version. All Fabric versions and the Forge/Neoforge 1.20.2 versions have this issue fixed. Forge 1.18.2-1.20.1 may have this fixed eventually, but no ETA on that yet.
