### ISSUE TITLE
Doesnt work on server

### ISSUE THREAD

**Issue by ADGParadox** [Apollounknowndev/tectonic#110]
i have the mod installed client side, serverside and the datapack placed into the worl folder but the world generation is vanilla yet when i use didtant horizons the lods show the tectonic generation

**Comment by Apollounknowndev** [comment]
If the LODs are still showing Tectonic generation, it's not a Tectonic issue.

**Comment by ADGParadox** [comment]
whats the ID for the server then so the world generates with tectonic

**Comment by Apollounknowndev** [comment]
There's no id to set, tectonic overrides the vanilla world types
