### ISSUE TITLE
(Feature Request) Increasing generation beyond vanilla world height with compatible mods

### ISSUE THREAD

**Issue by ReallyJustColin** [Apollounknowndev/tectonic#111]
Would it be possible to create a feature where you can change the world height and depth settings in the config to increase generation max height? For example there is a datapack/mod that increases the height to 2032 world height and I would love to be able to make mountains go over the default limit of 300, especially with distant horizons making really far chunks visible from crazy distances. (P.S. I'm sorry, I don't know how to add the feature request indicator)

**Comment by Apollounknowndev** [comment]
Tectonic v2.3a adds a config option for increasing the build and generation height limits to y640.

**Comment by doppeltrouble** [comment]
i have used this config option and my game will still not generate any blocks above 320 (minecraft default build height) and just turn the tops of my mountains into a Plateau

**Comment by ToxicStoxm** [comment]
> i have used this config option and my game will still not generate any blocks above 320 (minecraft default build height) and just turn the tops of my mountains into a Plateau

If you didn't find a solution this might help: https://www.reddit.com/r/feedthebeast/comments/1cpp17x/terraforged_at_home/

**Comment by doppeltrouble** [comment]
thanks
