### ISSUE TITLE
[1.20.1] Lava Rivers generating without Lava when Spelunkery is installed.

### ISSUE THREAD

**Issue by ambientNexus** [Apollounknowndev/tectonic#112]
Every instance of an underground lava river appears to be lacking the lava.
![image](https://github.com/Apollounknowndev/tectonic/assets/53546918/5bed6dc0-7870-4bc8-b90b-66a8de683579)
![2024-03-27_18 24 41](https://github.com/Apollounknowndev/tectonic/assets/53546918/261ad0de-b5a5-4b71-b0ef-3a786c040226)
![2024-03-27_18 25 45](https://github.com/Apollounknowndev/tectonic/assets/53546918/c7f782d6-a5be-4bc6-8441-6a415db6d15b)
![2024-03-27_18 27 21](https://github.com/Apollounknowndev/tectonic/assets/53546918/cda93a08-938f-4fd7-b9c8-e1b225731295)

**Comment by Apollounknowndev** [comment]
What other mods are you using?

**Comment by ambientNexus** [comment]
> What other mods are you using?

Tested it a bit more and the issue only seems to appear with the mod Spelunkery installed (https://www.curseforge.com/minecraft/mc-mods/spelunkery), and I've got no idea why that would be the case.

**Comment by ambientNexus** [comment]
I'll repost the issue over there since it's most likely an issue on that mod's side.

**Comment by Apollounknowndev** [comment]
Just took a look at their code, it's definitely Spelunkery.
