### ISSUE TITLE
Ore distribution

### ISSUE THREAD

**Issue by sbsosa** [Apollounknowndev/tectonic#114]
Hi there, I wasn't sure where else to ask this since there isn't a discord. Since the mountains are so much taller with Tectonic, how does that affect ore distribution? I would assume that below y62, ores would generate the same as vanilla. Would love some more insight if possible! Thank you for all you do btw.

**Comment by Apollounknowndev** [comment]
Ore generation is identical to vanilla.

**Comment by sbsosa** [comment]
thanks!
