### ISSUE TITLE
Tectonic v2.3 requires Minecraft V1.20.2 or greater

### ISSUE THREAD

**Issue by NolanHewitt** [Apollounknowndev/tectonic#115]
"tectonic-fabric-1.20-2.3" breaks on start-up saying it requires 1.20.2 or newer, despite the mod listing saying its for any version between 1.19.3 and 1.20.4

Tested on Minecraft Version 1.20.1

**Comment by AlarkiusJay** [comment]
I'm sure it's an April Fools Joke (idk, since the install seemed really legit)

New Thought: Now I'm convinced

**Comment by AlarkiusJay** [comment]
> "tectonic-fabric-1.20-2.3" breaks on start-up saying it requires 1.20.2 or newer, despite the mod listing saying its for any version between 1.19.3 and 1.20.4
> 
> Tested on Minecraft Version 1.20.1

I'm sure it's an April Fools Joke (idk, since the install seemed really legit)

New Thought: Now I'm convinced

**Comment by Apollounknowndev** [comment]
Oops, didn't mean to do that 😅 
2.3a should be rolling out in the next few minutes to fix that.

**Comment by Apollounknowndev** [comment]
Fixed in v2.3a.
