### ISSUE TITLE
[1.18.2] Q: Extending world depth by manually editing data

### ISSUE THREAD

**Issue by Endgineer** [Apollounknowndev/tectonic#117]
I'm using a modified version of Terralith (for personal use only) and I've been able to successfully extend the world depth to, say `y -896`, and still see caves.

The issue is when I add Tectonic, despite the world depth still being extended from Terralith's side (i.e. bedrock is at y -896), there are no caves below `y -64` (I assume this is because Tectonic overrides Terralith).

I'm looking to manually modify the Tectonic data files to get caves/features to spawn/extend below `y -64`. So far, I've tried modifying the `depth.json` files alone first, then also any files that seemed to reference/use a y-level of -64 or -60 or similar. The result of this has been an ocean world with an ocean depth that extends to `y -896`.

I'm relatively new to datapacks, especially world gen. Would it be possible to get pointers on which files need to modified to achieve this, or if this is even possible?

**Comment by Kyles1201** [comment]
Any update on this?

**Comment by Endgineer** [comment]
> Any update on this?

Unfortunately I was unable to figure it out on my own and just gave up.
