### ISSUE TITLE
1.19.2 v2.3, data pack not validating when I use the ''increased_height'' setting within config.

### ISSUE THREAD

**Issue by JimBob-bb** [Apollounknowndev/tectonic#118]
I want to use the setting for my world but it doesn't work currently.

**Comment by Apollounknowndev** [comment]
Fabric or Forge?

**Comment by JimBob-bb** [comment]
Forge

**Comment by Apollounknowndev** [comment]
Can't replicate the issue on a fresh Forge 1.19.2 instance with just Tectonic. Can you provide a mod list?
![2024-04-03_14 43 01](https://github.com/Apollounknowndev/tectonic/assets/102649729/8b8364b9-bd9c-4217-80bc-a8d22070227f)

**Comment by Apollounknowndev** [comment]
> It also says within the data pack folder ,when creating a new world, that increased height is ''Made for a newer version of Minecraft''. I'm playing on 1.19.2, same version as the mod. I've also tried the newest version of the mod (2.3.1) and I'm having the same issue, I hope that information helps a bit.

The "Made for a newer version of Minecraft" warnings can be safely ignored, they're a byproduct of the fact that the same datapack files are used for every Tectonic version.

**Comment by JimBob-bb** [comment]
I'm using the CurseForge mod loader, I've downloaded the pack to a file that requires to be imported into CurseForge. It should also download the config with it, sorry if this issue is all down to me, as I would've wasted your time. Sorry in advance if that turns out to be the case, thank you for the help.

[modpack..zip](https://github.com/Apollounknowndev/tectonic/files/14865050/modpack.zip)

**Comment by JimBob-bb** [comment]
I think that I may have found the issue, I removed the mod called essential, a multiplayer mod, now it works. Sorry for wasting your time my friend. Thank you for your time.
