### ISSUE TITLE
v2.3.1 Quilt 1.20.1 - Not generating above 320 with increased height enabled.

### ISSUE THREAD

**Issue by onecreq** [Apollounknowndev/tectonic#119]
As said, the generation of mountains cuts off/plateaus at y320, not generating anything above that. Terrain scale is set to 1.35, horizontal mountain range is 0.215, increased height is set to true. I am using other mods, though the only two that even slightly modify world generation is Create and Farmer's Delight, neither of should mess with that I feel like.
![image_2024-04-02_183144381](https://github.com/Apollounknowndev/tectonic/assets/87343926/d96c03ba-9144-40b7-b31b-80d9b00cea86)
![image_2024-04-02_183157181](https://github.com/Apollounknowndev/tectonic/assets/87343926/9ec85565-db3a-48ed-be22-487d6e425071)

**Comment by Apollounknowndev** [comment]
Fixed in v2.3.1a. Old worlds are not retroactively fixed.
