### ISSUE TITLE
[1.19.2] v2.3.1 Small terrain scale making the river too wide

### ISSUE THREAD

**Issue by Rad586** [Apollounknowndev/tectonic#120]
**Fabric 1.19.2, tectonic v2.3.1.**
**Other biome-related mods:** Terralith, WWOO, Not Just Biomes(unlikely to matter, since it's working fine before changing the terrain scale).
A small terrain scale makes the world generation smoother, but it also makes rivers too wide and shallow. 
![image](https://github.com/Apollounknowndev/tectonic/assets/99306685/20dd1d89-7ea0-4cee-92f1-5794435faf5e)

It's quite usual to see structures generating with part of them in the river.

![image](https://github.com/Apollounknowndev/tectonic/assets/99306685/77ecfc1b-ba1c-4ca9-b389-9e53e1ae7e2b)
![image](https://github.com/Apollounknowndev/tectonic/assets/99306685/786d4d55-b8f9-4efb-aec5-1fde676c2388)

And somehow the structures are more likely to generate on slopes, making part of them popping out, or sink in the terrain. 
Maybe it's because there's more slopes for them to do so, though. 

![image](https://github.com/Apollounknowndev/tectonic/assets/99306685/457f894b-074f-43ec-bd07-eccd684fc64d)

**Current tectonic config:** 
https://gist.github.com/Rad586/8023a906efd015798ba99eeab464779d

**Comment by Apollounknowndev** [comment]
This is not really fixable without making rivers thinner and deeper by default. May revisit this issue in the future, but for now it's not on my list of issues to fix.
