### ISSUE TITLE
[SUGGESTION] A bit more documentation on each config setting

### ISSUE THREAD

**Issue by Sunconure11** [Apollounknowndev/tectonic#123]
For one, I am not sure what terrain_scale does.

**Comment by Hati-** [comment]
Testing suggest that `terrain_scale` effects how the terrain generation height is scaled.

Here are photos taken from the same position and seed with the Terralith mod installed:

`"terrain_scale": 1.125` (default)
![2024-04-04_14 04 19](https://github.com/Apollounknowndev/tectonic/assets/10211721/b771dbc0-7f54-4aba-b4a6-8989fc66cf9c)

`"terrain_scale": 0.5625` (half of default)
![2024-04-04_14 06 13](https://github.com/Apollounknowndev/tectonic/assets/10211721/8dc4f18d-a991-48af-bd92-fd6945a45869)

**Comment by Apollounknowndev** [comment]
Information on the `terrain_scale` setting will be in v2.3.3.

**Comment by JimBob-bb** [comment]
Is there anyway to make the mountains wider as well as tall?
