### ISSUE TITLE
Rainforest biome spawns much higher up than usual

### ISSUE THREAD

**Issue by Qzertje** [Apollounknowndev/tectonic#125]
The rain forest biome from Biomes O Plenty spawns much higher up than usual, normally it spawns next to a river and is very flat, but whem I install tectonic, it spawns high up and sometimes even on mountains.
![Screenshot_20240405_120816_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/Apollounknowndev/tectonic/assets/110260736/8736d14f-57f1-4325-b9e0-2eeff11b128a)

**Comment by Apollounknowndev** [comment]
Biomes don't determine terrain, the biome is simply adapting to Tectonic's terrain. WAI.
