### ISSUE TITLE
tectonic.json config changes not saving

### ISSUE THREAD

**Issue by SlackinLackin** [Apollounknowndev/tectonic#127]
In the tectonic.json config, every time I change deeper oceans to false or desert dunes to true, they keep reverting back to their original values. The experimental values save, but the feature values do not. 

I know it's not cause I'm forgetting to save, I tested that out by changing both the experimental values and the feature values. The experimental values saved, but the feature values still reverted back.

Here's my config file (I deleted the comments just now to make it more readable):

{
  "experimental": {
    "horizontal_mountain_scale": 0.25,
    "increased_height": false,
    "terrain_scale": 0.9
  },
  "features": {
    "deeper_oceans": false, (this keeps turning back to 'true')
    "desert_dunes": true, (this keeps turning back to 'false')
    "lava_rivers": true,
    "underground_rivers": true
  },
  "legacy": {
    "enabled": false
  },
  "mod_enabled": true
}

And I don't know if this issue needs a world seed, but I'll provide one if it does.

**Comment by Apollounknowndev** [comment]
Looks like the deeper oceans and desert dunes toggles would switch with each other every time the config was loaded, whoops. Fixed in v2.3.4.
