### ISSUE TITLE
Weird biome/temperature mountain

### ISSUE THREAD

**Issue by IntM4rco** [Apollounknowndev/tectonic#130]
Badlands with snow but still hot (watch Tough As Nails guy)

<img width="1440" alt="Screenshot 2024-04-12 alle 16 49 05" src="https://github.com/Apollounknowndev/tectonic/assets/124934175/53222dbc-cb65-4db1-97c8-7b4132f3073d">

**Comment by Apollounknowndev** [comment]
That's a Snowy Badlands biome from Terralith.
https://stardustlabs.miraheze.org/wiki/Snowy_badlands

**Comment by IntM4rco** [comment]
I dont have Terralith, maybe WWOO?

**Comment by Apollounknowndev** [comment]
Ah, it's WWOO then. It also makes the Badlands biome snowy, I completely forgot about that

**Comment by IntM4rco** [comment]
Ty, i reported that on their discord.
