### ISSUE TITLE
Tectonic crams structures into a single place

### ISSUE THREAD

**Issue by Driestcombee** [Apollounknowndev/tectonic#131]
This seems like a reoccuring issue with medium-sized modded structures but this is the most apparent with large structures such as the ones from When Dungeons Arise. (On Fabric)
![broken structure](https://github.com/Apollounknowndev/tectonic/assets/142123085/3f0c79d8-b501-400c-8b80-fe974c98e787)
Mods used:
William Whythers' Expanded Ecosphere
When Dungeons Arise
When Dungeons Arise: Seven Seas
Tectonic
Towers of the Wild Modded
Debugify
Dynamic FPS
Entity Culling Fabric
Distant Horizons
Lithium
owo (this is a mod library)
Fabric Waystones
Krypton
LazyDFU
Towns and Towers
Bosses of Mass Destruction (Beta)
FerriteCore 
Seed: 4923738770517879021

**Comment by Driestcombee** [comment]
I'm not sure if this is a When Dungeons Arise Issue or another issue

**Comment by Driestcombee** [comment]
![totally normal world gen](https://github.com/Apollounknowndev/tectonic/assets/142123085/eb1ff741-c270-4620-9ffa-a99f3d5e4f4d)
Another example

**Comment by Driestcombee** [comment]
![another perfectly normal structure](https://github.com/Apollounknowndev/tectonic/assets/142123085/289ef915-3183-4dbe-8dcd-cc20811431cb)

**Comment by Explosif3005** [comment]
I dont have any screenshot as of now, but village mods, like CTOV, cause MASSIVE problem, like when a house generate in the air there is a thin platform of two block that generate (weird), structure that generate in wall...

**Comment by Apollounknowndev** [comment]
This is a When Dungeons Arise issue. Looking at their code, they have their structures set up so major structures and minor structures both try to spawn in the exact same places 100% of the time. I will be leaving the WDA devs a report about it.

**Comment by Apollounknowndev** [comment]
Turns out When Dungeons Arise fixed this issue months ago way back in December, they just didn't upload the fix to Modrinth. Download the mod from Curseforge until 2.1.58 is on Modrinth.

**Comment by Driestcombee** [comment]
thx
