### ISSUE TITLE
No ocean side cliffs

### ISSUE THREAD

**Issue by Qzertje** [Apollounknowndev/tectonic#132]
Ocean side cliffs don't seem to generate
![image](https://github.com/Apollounknowndev/tectonic/assets/110260736/3dd6b9c9-2a9c-4094-a7d3-90583034ba2c)
![image](https://github.com/Apollounknowndev/tectonic/assets/110260736/35fc1084-6909-4ae8-bdbe-d24e4d25de26)
![image](https://github.com/Apollounknowndev/tectonic/assets/110260736/67fd4969-f603-4f3e-99b2-8617f60c7170)

**Comment by Apollounknowndev** [comment]
They don't generate ~60% of the time now, intended change.
