### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by Sm982** [Apollounknowndev/tectonic#133]
Downloaded the mod and installed it. Didn't see any configuration options so I thought they were preset. Nope, terrain still looked like original minecraft. Installed the data pack and still the same. 

Is this normal? Am I installing it or using it properly? There is no documentation nor videos.

**Comment by Apollounknowndev** [comment]
Definitely way too late to respond to this but I'll leave a comment for anyone who sees this in the future.

Regular flat terrain is both a part of vanilla and Tectonic, so you may just see that. Run `/locate biome minecraft:jagged_peaks` and teleport to the mountains to see if you're playing with vanilla or Tectonic. If it's vanilla mountains, you probably didn't install the mod/datapack correctly.
