### ISSUE TITLE
CTOV + Tectonic, embedding of structures in the terrain

### ISSUE THREAD

**Issue by Explosif3005** [Apollounknowndev/tectonic#135]
Version : 1.20.1
Mod : CTOV + Tectonic + (optionel) Terralith
I have observed that while exploring world were tectonic is active village created by CTOV, have problem generating in terrain with huge variation of height such as mountain. I have left here a number of screenshot of exemple of such error of generation. Where part of the generated structure embed themselfs in walls.
![2024-04-18_10 18 12](https://github.com/Apollounknowndev/tectonic/assets/75031787/a32ec903-d494-4883-a6d3-8a9b5f39c9d2)

![2024-04-18_10 17 16](https://github.com/Apollounknowndev/tectonic/assets/75031787/efd37b34-c33c-44e5-8750-e2b685e64ded)
![2024-04-18_10 18 04](https://github.com/Apollounknowndev/tectonic/assets/75031787/4bba4ce4-2553-41ed-bd24-7b4b6d0e7417)

![2024-04-18_10 16 41](https://github.com/Apollounknowndev/tectonic/assets/75031787/892f1a4c-d421-4e3e-9e37-0c2454035629)
![2024-04-18_10 16 54](https://github.com/Apollounknowndev/tectonic/assets/75031787/37915501-3828-4805-90f2-916bac68799a)

![2024-04-18_10 06 51](https://github.com/Apollounknowndev/tectonic/assets/75031787/32597ac8-1aa1-4f54-82a1-cde01063eb4f)
![2024-04-18_10 07 25](https://github.com/Apollounknowndev/tectonic/assets/75031787/e3992190-6fd5-4854-a18e-4b39f6d36951)

![2024-04-18_10 06 23](https://github.com/Apollounknowndev/tectonic/assets/75031787/125958c0-346a-4857-8b2f-0b12ac6a09c7)
![2024-04-18_10 06 41](https://github.com/Apollounknowndev/tectonic/assets/75031787/3400e30f-9af4-4634-bb6d-4b0b66d6f39f)

![2024-04-18_10 06 08](https://github.com/Apollounknowndev/tectonic/assets/75031787/6fd796d6-149c-45df-8c9f-5b72d0d6fb0b)
![2024-04-18_10 06 12](https://github.com/Apollounknowndev/tectonic/assets/75031787/4a87032c-581f-4095-bf3c-d957eca64afa)

![2024-04-18_10 05 16](https://github.com/Apollounknowndev/tectonic/assets/75031787/02691067-e83b-4b30-8587-dc28ab0b74f6)

![2024-04-18_10 03 23](https://github.com/Apollounknowndev/tectonic/assets/75031787/55e47ea0-de05-43e2-b04b-120d36bd59a0)
![2024-04-18_10 03 40](https://github.com/Apollounknowndev/tectonic/assets/75031787/faf171fb-7ee2-4925-bd19-977c553de859)
![2024-04-18_10 05 05](https://github.com/Apollounknowndev/tectonic/assets/75031787/dc2d7432-1b12-49e3-be60-bcf090234178)

![2024-04-18_10 03 12](https://github.com/Apollounknowndev/tectonic/assets/75031787/0d460edd-4096-45ac-9680-90216f00fa8c)
![2024-04-18_10 03 19](https://github.com/Apollounknowndev/tectonic/assets/75031787/448ae2d6-3f25-4c07-ae26-cf3418f47a0e)

**Comment by Apollounknowndev** [comment]
All of these issues exist in vanilla as well, can't fix

**Comment by polonixpolska** [comment]
try using lithostiched, it positions structures into the right positions i think. hope i could help :)
