### ISSUE TITLE
[1.20.1] Biomes generate as oceans instead of proper biomes.

### ISSUE THREAD

**Issue by Reshy** [Apollounknowndev/tectonic#137]
With Tectonic:
![image](https://github.com/Apollounknowndev/tectonic/assets/2096384/93a60ef3-6f25-4d5e-aabc-7a42d964d36a)

Without Tectonic:
![image](https://github.com/Apollounknowndev/tectonic/assets/2096384/14309525-ae75-42dd-93bb-e24e1ab52fdc)

Map showing the biome is clearly supposed to generate as a brushland, as well as outlying structures for that biome generating in water:
![image](https://github.com/Apollounknowndev/tectonic/assets/2096384/917542dd-ac4d-4bfe-ae5e-c035c02143a7)

Biomes with Tectonic can and do still generate properly, though it seems like there's a high chance that the biome gets replaced with ocean generation:
![image](https://github.com/Apollounknowndev/tectonic/assets/2096384/9dfbbe8b-5308-4db0-83d1-0df557797207)

**Comment by Apollounknowndev** [comment]
Installing Tectonic on an existing world is not supported.

**Comment by Reshy** [comment]
> Installing Tectonic on an existing world is not supported.

I think you misunderstood, I generated starting with Tectonic then turned it off.
