### ISSUE TITLE
Server world don't generate like tectonic should

### ISSUE THREAD

**Issue by Aznoq3** [Apollounknowndev/tectonic#138]
Hey, I have been trying to create a server that use both tectonic and terralith for the world generation in fabric 1.20.4.
However, when we connect to the new world, only terralith generate and the amazing mountains of tectonic doesn't show up.
We didn't modify the config at all.

Can you please help us ?

**Comment by lolpowerluke** [comment]
did you add the terratonic datapack to 
serverfolder > world > datapacks
