### ISSUE TITLE
1.20.6 support?

### ISSUE THREAD

**Issue by Night4-dev** [Apollounknowndev/tectonic#141]
hello when are you gonna uppdate it to 1.20.6?

**Comment by Apollounknowndev** [comment]
fabric/datapack 1.20.5 already works on 1.20.6
neoforge 1.20.5/6 will take a few more days

**Comment by Night4-dev** [comment]
ok then il use the datapack until neoforge is out

**Comment by Apollounknowndev** [comment]
Proper Neoforge 1.20.5/6 support has released.
