### ISSUE TITLE
World Gen Issues with Server (1.20.4)

### ISSUE THREAD

**Issue by The-Chog** [Apollounknowndev/tectonic#149]
My world is generating with huge cut offs of biomes. 

Just cutting mountains in half and I don't know why

![2024-05-26_22 39 05](https://github.com/Apollounknowndev/tectonic/assets/170868988/b646fa64-77a9-48aa-bdc9-6eb4a925329c)

**Comment by Hyporeal** [comment]
Did you happen to apply Tectonic to a new or existing world?

**Comment by Apollounknowndev** [comment]
Don't add Tectonic to an existing world.
