### ISSUE TITLE
[1.20.1] Crash On Spawn Using Increased Height

### ISSUE THREAD

**Issue by S3555** [Apollounknowndev/tectonic#151]
there no other mods in use besides Tectonic. I can spawn after world creation, but when i move or look around the game crashes. I also noticed that my creative inventory is blank, which is weird but worth noting.

**Comment by S3555** [comment]
update: i somehow got everything to load and generate fine. inventory screen isnt blank anymore. but it still crashes after a bit of playing and loading chunks

**Comment by Apollounknowndev** [comment]
Send crash report

**Comment by S3555** [comment]
> Send crash report

https://mclo.gs/MyJnEiO

**Comment by Apollounknowndev** [comment]
That looks like a rendering related crash, not a worldgen related crash.
