### ISSUE TITLE
[Datapack] World type Large Biomes not functioning

### ISSUE THREAD

**Issue by PMaujean** [Apollounknowndev/tectonic#152]
Hello,

Large Biomes are not functioning with the datapack.

Versions tested :
 - MC 1.20.4 w/ DP 2.2.1
 - MC 1.20.4 w/ DP 2.2.2
 - MC 1.20.6 w/ DP 2.2.1
 - MC 1.20.6 w/ DP 2.2.2
 
Biomes Map previewed with World Preview ( seed qz6QMvccTMOvassF ) : No differences between normal and large

![1 20 4 datapack](https://github.com/Apollounknowndev/tectonic/assets/56881137/e6e076bd-eb7d-449e-9e39-b53f6cebc331)

 Large Biomes control map : MC 1.20.6 w/ Fabric, tectonic v2.3.4 :
 
![1 20 6 fabric](https://github.com/Apollounknowndev/tectonic/assets/56881137/a117f848-d2dc-4f61-bf9e-996724ca6892)

**Comment by Apollounknowndev** [comment]
Known issue. Due to technical quirks in datapacks, there can either be support for other world types (Large Biomes/Superflat) or support for upgrading worlds from Tectonic v1 to v2 (the current behavior). 

In Tectonic releases for 1.21 and above, other world types will be supported.
