### ISSUE TITLE
small comment

### ISSUE THREAD

**Issue by yu234567** [Apollounknowndev/tectonic#153]
Many peaks have an excessive amount of iron ore.
![2024-06-02_00 07 54](https://github.com/Apollounknowndev/tectonic/assets/111959644/2fc0b027-d8a1-4ba7-8715-dee261e9c113)
![2024-06-02_00 09 22](https://github.com/Apollounknowndev/tectonic/assets/111959644/5f9e7598-1985-4379-bf83-242eceae8b9f)

**Comment by Apollounknowndev** [comment]
Intended vanilla behavior. See the ore distribution chart [here](https://minecraft.wiki/w/Ore#/media/File:1-18-ore-distribution.jpg).
