### ISSUE TITLE
new update makes the mod not load minecraft

### ISSUE THREAD

**Issue by lilsherm09** [Apollounknowndev/tectonic#154]
the newest update (posted 6/4/24) just gives you a error when loading  minecraft, i tested this with just tectonic loaded and same thing happened. 
![image](https://github.com/Apollounknowndev/tectonic/assets/116927046/731b27cb-dc16-46a2-95c4-c7c4f11042a1)

**Comment by Thunderrock424242** [comment]
got the same but in crash form
[latest.log](https://github.com/user-attachments/files/15571216/latest.log)

**Comment by Vinzound** [comment]
The same with me.

**Comment by kyber-6** [comment]
Same here.

**Comment by deltaminimal** [comment]
Same!

**Comment by Camawama** [comment]
SAME
[crash-2024-06-04_19.18.40-client.txt](https://github.com/user-attachments/files/15571620/crash-2024-06-04_19.18.40-client.txt)

**Comment by zekurom** [comment]
Same

**Comment by MattB70** [comment]
Looks like Java 21 was used to make this latest build. We have to wait for another build.

**Comment by RosivDamotil** [comment]
Sad my Server has to stay offline until this is solved. :(

**Comment by Mystifyed** [comment]
Same

**Comment by bluezod** [comment]
same problem.

Downgrading the version to 2.3.4 does work tho.

**Comment by SeagalKru** [comment]
+1

**Comment by KyrDerz** [comment]
+1

**Comment by Apollounknowndev** [comment]
Hotfix will roll out very soon.

**Comment by AqueleHaru** [comment]
> Hotfix will roll out very soon.

waiting <3

**Comment by Apollounknowndev** [comment]
Fixed in v2.3.5a.
