### ISSUE TITLE
tectonic.json - Possible to mimic "vanilla" terrain, or only use the extra features?

### ISSUE THREAD

**Issue by HatTrkPatrk** [Apollounknowndev/tectonic#156]
Hi, sorry if this is a dumb question, I am curious if it's possible to setup the tectonic.json configuration settings so that the terrain itself isn't changed (as close to what the terrain would be without tectonic as possible) while still adding the features like underground rivers and deeper oceans. So I just wanted to check if e.g. setting horizontal_mountain_scale and terrain_scale to certain values would make this happen. If it's not possible, that's fine. Thank you!

[EDIT]
If it isn't actually possible to do what I described above, then is it instead possible somehow to only have the extra features of Tectonic (deeper oceans, desert dunes, lava rivers, underground rivers)? Thank you again

**Comment by CheetahCyberBoi** [comment]
I second this. I added Tectonic for the extra features but dislike how smooth it made the terrain. Is this possible?

**Comment by Apollounknowndev** [comment]
Tectonic's terrain shaping and the smoother terrain is too critical to the underlying infrastructure of the pack to be able to be toggled.
