### ISSUE TITLE
possibility of changing world gen height limit in config?

### ISSUE THREAD

**Issue by saccharinesky** [Apollounknowndev/tectonic#157]
in tectonic.json, the increased_height variable lets you change the max build and world gen height to 640; is it possible to change this value or add an option to change it to one that is even greater?

**Comment by Apollounknowndev** [comment]
There's no straightforward way to implement a simple number config for the max height instead, and adding an XL Increased Height datapack would only leave the project more bloated on the backend. 

I might provide a tutorial on how to modify the pack yourself, but no clue when that'd be made.
