### ISSUE TITLE
crash on my modpack when i load it 

### ISSUE THREAD

**Issue by Thunderrock424242** [Apollounknowndev/tectonic#158]
mod list is in latest.log

[launcher_log.txt](https://github.com/user-attachments/files/15795330/launcher_log.txt)
[latest.log](https://github.com/user-attachments/files/15795331/latest.log)
[debug.log](https://github.com/user-attachments/files/15795333/debug.log)

**Comment by Apollounknowndev** [comment]
Rendering error with `livingthings`, not Tectonic.

**Comment by Thunderrock424242** [comment]
> Rendering error with `livingthings`, not Tectonic.

How would you explain then when I turn tectonic off it fixes it
