### ISSUE TITLE
Tectonic and Lithosphere Height Limited 1.20.6

### ISSUE THREAD

**Issue by makumaku1974** [Apollounknowndev/tectonic#159]
![2024-06-14_13 05 34](https://github.com/Apollounknowndev/tectonic/assets/129804277/f6a1a427-4f3a-4e16-93fa-1c5c3fc29e9b)

To my guess i find the mods quite appealing together but recently following the guides of a youtuber AsianHalfSquat as his version was 1.20.1 and I'm in 1.20.6. 

I'm really stuck behind my computer thinking wtf did i do wrong this time. I wanted to create a world to venture on the peaks and seeing cut off mountain peaks is just awful. I've also installed multiple build height extended mods to suffice the problem and still the problem occurred. Please guide me. Tnx.

**Comment by Apollounknowndev** [comment]
Lithosphere isn't compatible with Tectonic, you can only choose one. One will forcibly override the other (and it looks here like Tectonic won).

Don't use other height limit mods to fix the issue as they'll likely break with Tectonic. Go to `tectonic.json` in your instance config folder and enable the `increased_height` setting.

**Comment by makumaku1974** [comment]
Ill come back with results again.

**Comment by makumaku1974** [comment]
![2024-06-16_19 32 20](https://github.com/Apollounknowndev/tectonic/assets/129804277/7bae799d-99d7-4cd8-a50e-91e9ec17ff18)

![2024-06-16_19 30 40](https://github.com/Apollounknowndev/tectonic/assets/129804277/97501ba3-3184-418b-ad44-c1cf24f0b6c1)
![2024-06-16_19 31 21](https://github.com/Apollounknowndev/tectonic/assets/129804277/70094750-f7fc-4859-84b4-b534a2fbad3d)
![2024-06-16_19 32 08](https://github.com/Apollounknowndev/tectonic/assets/129804277/24500536-658c-40a2-a866-9f0d5e0e1327)

![2024-06-16_19 30 37](https://github.com/Apollounknowndev/tectonic/assets/129804277/37347f5a-17c2-46bb-94a5-e0bfa5b90ec3)

Both actually works well. But yeah Lithosphere is just too heavy on mountain ranges than mountains itself yet still compatible.

**Comment by rauloruclu13-sudo** [comment]
why i dont have "increased height" in config?: 
{
  "biomes": {
    "temperature_multiplier": 1.0,
    "temperature_offset": 0.0,
    "temperature_scale": 0.25,
    "vegetation_multiplier": 1.0,
    "vegetation_offset": 0.0,
    "vegetation_scale": 0.25
  },
  "caves": {
    "carvers_enabled": true,
    "cheese_additive": 0.27,
    "cheese_enabled": true,
    "depth_cutoff_size": 0.1,
    "depth_cutoff_start": 0.1,
    "noodle_additive": -0.075,
    "noodle_enabled": true,
    "spaghetti_enabled": true
  },
  "continents": {
    "continents_scale": 0.13,
    "erosion_scale": 0.25,
    "flat_terrain_skew": 0.1,
    "jungle_pillars": true,
    "ocean_offset": -0.8,
    "ridge_scale": 0.25,
    "river_lanterns": true,
    "rolling_hills": true,
    "underground_rivers": true
  },
  "general": {
    "mod_enabled": true,
    "snow_start_offset": 128
  },
  "global_terrain": {
    "elevation_boost": 0.0,
    "lava_tunnels": true,
    "max_y": 1500,
    "min_y": -500,
    "ultrasmooth": false,
    "vertical_scale": 1.125
  },
  "islands": {
    "enabled": true,
    "noise_multiplier": 1.0,
    "noise_offset": 0.0,
    "noise_scale": 0.11
  },
  "minor_version": 1,
  "oceans": {
    "deep_ocean_depth": -0.45,
    "monument_offset": -30,
    "ocean_depth": -0.22,
    "remove_frozen_ocean_ice": false
  }
}
