### ISSUE TITLE
v2.3.5a & b doesn't load on the new Fabric 0.92.2 version

### ISSUE THREAD

**Issue by AlarkiusJay** [Apollounknowndev/tectonic#162]
stated in the title, don't know if others have this problem show up in their logs...

![Modrinth App 6_17_2024 3_12_33 PM](https://github.com/Apollounknowndev/tectonic/assets/84819182/24b70e47-e4e7-4ebd-acd3-0de4a9511359)

the third line in highlight

**Comment by dejacrack** [comment]
i'm having the same issue which sucks :/

**Comment by Apollounknowndev** [comment]
Those errors don't actually prevent the mod from loading.
![image](https://github.com/Apollounknowndev/tectonic/assets/102649729/f1f6671f-a3de-4e05-aa08-8ede2ce3c332)
