### ISSUE TITLE
when i try to create a new world with 1.19.2 version it doesnt let me and says "failed to verify datapacks"

### ISSUE THREAD

**Issue by WorestWasTaken** [Apollounknowndev/tectonic#165]
![image](https://github.com/Apollounknowndev/tectonic/assets/137095154/2d848a81-914b-444b-bfe4-165873b5d16e)

**Comment by Apollounknowndev** [comment]
1.19.2 is no longer a supported version, and there's not enough information for me to reproduce the issue.
