### ISSUE TITLE
Floating Biomes

### ISSUE THREAD

**Issue by yunus-cakir** [Apollounknowndev/tectonic#166]
I really love Tectonic but recently I noticed floating biomes!
![image](https://github.com/Apollounknowndev/tectonic/assets/83448525/6f0d4ca6-0018-47cf-8d7a-e430abbeea54)

And by the way, is there a solution for the other little structure additions to be complete compatible for Tectonic?
MVS:
- Other Decoration/pile
- Other Decoration/windmill
- well/small Well
![image](https://github.com/Apollounknowndev/tectonic/assets/83448525/79d20370-2c4c-4043-baaa-d3a4856a9360)

**Comment by Apollounknowndev** [comment]
This can happen in some edge cases where an underground river cuts through oddly shaped terrain, not really fixable unfortunately.
