### ISSUE TITLE
Coastside terrain Generation

### ISSUE THREAD

**Issue by Aertic** [Apollounknowndev/tectonic#167]
Sometimes when shorelines generates, both near rivers, lakes and seas, tectonic generates a very steep, inaccessible and bad looking transition from the water body to terrain.

I'm not sure if it's possible to fix this, but I've been told many people complain about this and that I should make an issue on Github. I attached a photo below.

![image](https://github.com/Apollounknowndev/tectonic/assets/63727339/7b653f71-985a-4646-bfd4-a34065590fc5)

**Comment by Pinguus** [comment]
hey do you know how to make tectonic work. i just installed it but its considerrerd incompatible and i believe it isnt affecting my game at all

**Comment by Aertic** [comment]
Another example of what I'm talking about
![2024-06-20_19 22 43](https://github.com/Apollounknowndev/tectonic/assets/63727339/222a80d8-5312-487f-b818-f199189f64b7)

This renders this side of the island completely useless/entire islands are useless, since there's really no easy way to get up and would require a lot of time for terraforming

**Comment by Apollounknowndev** [comment]
The cliff generation itself is intended. Vanilla also has cliffs to transition between oceans and higher terrain, especially near mountains.

As for the beach biome being there, that's a side effect of Terralith's biome layout moving Beaches to generating where they don't in the vanilla biome layout. Normally they're supposed to be entirely Stony Shore. A fix for this may happen at some point, but it's not currently high up on my priority list.

**Comment by MattB70** [comment]
It feels as if 90% of coasts are too steep to make use of. You can sort of solve it by cranking your terrain_scale waaaaaay down, but then your world is flat. These sort of coasts feel too common to be interesting imo.

**Comment by Aertic** [comment]
Agreed
