### ISSUE TITLE
version 1.21 is considered incompatable

### ISSUE THREAD

**Issue by Pinguus** [Apollounknowndev/tectonic#168]
I dont know how to fix. help appreciated

**Comment by Apollounknowndev** [comment]
Can you elaborate more? Do you mean the mod isn't loading?

**Comment by Aertic** [comment]
When you try to use tectonic 1.21 it shows and incompatible in minecraft + map.jacobsjo.eu - can cofirm this

**Comment by Aertic** [comment]
but it seems to work fine, just shows as incompatible

**Comment by Pinguus** [comment]
> Can you elaborate more? Do you mean the mod isn't loading?

the mod demonstrated as incompatible. I figured out i had the mod in the wrong folder. my old optifine one

**Comment by Apollounknowndev** [comment]
Not enough info. If this issue is still relevant please create a new issue with more details.
