### ISSUE TITLE
Lava at y level -55 updates incorrectly and causes crash when chunk is loaded

### ISSUE THREAD

**Issue by KingKottlewing** [Apollounknowndev/tectonic#170]
Like the title says, occasionally lava at y level -55 will fail to update neighbours and cause a crash when the chunk is loaded
[crash-2024-06-21_02.02.14-server.txt](https://github.com/user-attachments/files/15926379/crash-2024-06-21_02.02.14-server.txt)
[crash-2024-06-21_02.17.36-server.txt](https://github.com/user-attachments/files/15926381/crash-2024-06-21_02.17.36-server.txt)

Deleting the chunk and regenerating it does not fix it

**Comment by Apollounknowndev** [comment]
Not caused by Tectonic.
