### ISSUE TITLE
"To use this datapack, Terratonic must load above Terralith in the datapack list!" how can i ensure that on a server

### ISSUE THREAD

**Issue by TheRsKing** [Apollounknowndev/tectonic#171]

**Comment by Aertic** [comment]
I did it by downloading the level.dat,  finding datapacks in there and moving terratonic manually up

**Comment by Aertic** [comment]
(The tool for this is called NBT Explorer)

**Comment by TheRsKing** [comment]
> I did it by downloading the level.dat, finding datapacks in there and moving terratonic manually up

But to get this file, you have to start the server already once, and then it is already too late (because the generation has already started), isn't it?

**Comment by Aertic** [comment]
Just delete everything else except level.dat and overwrite it
Should work

**Comment by TheRsKing** [comment]
thanks! ;)

**Comment by Aertic** [comment]
np, lmk if you need anything else

**Comment by Apollounknowndev** [comment]
Terratonic will automatically load above Terralith if it remains alphabetically after Terralith. Just don't rename the files and you're fine.

**Comment by TheRsKing** [comment]
oh that makes things a lot easier thanks :)
