### ISSUE TITLE
Terratonic 1.21

### ISSUE THREAD

**Issue by Aertic** [Apollounknowndev/tectonic#172]
Is there any ETA on terratonic 1.21? Is the current version compatible?

**Comment by RyderGithu** [comment]
still waiting...

**Comment by Apollounknowndev** [comment]
Apologies for the extended wait, it's out now and you can get it [here](https://modrinth.com/datapack/terratonic/version/3.2).

**Comment by Aertic** [comment]
No problem,  i solved it in the meantime by pregenerating a world with the modded version. Thanks a lot for updating.
