### ISSUE TITLE
No Caves datapack compatibility

### ISSUE THREAD

**Issue by vico93** [Apollounknowndev/tectonic#173]
Is Tectonic compatible with mods that disable the "new" noise caves like the retro caves datapack of [No Caves](https://modrinth.com/datapack/no-caves)?

**Comment by Apollounknowndev** [comment]
![image](https://github.com/Apollounknowndev/tectonic/assets/102649729/81d82abf-e8d9-4c2e-bb9a-8406e07cb705)
