### ISSUE TITLE
Huge Cliffs

### ISSUE THREAD

**Issue by OfficiallyCrazy** [Apollounknowndev/tectonic#174]
This issue may not be related to tectonic.
![image](https://github.com/Apollounknowndev/tectonic/assets/52561202/469eb857-57c9-4413-90e7-4550d8766bc3)
When generating new chunks. most of the time I have huge cliffs or valley's formed like the one showed on the image. 

Am I perhaps meant to use Terrablender to fix this?

**Comment by Apollounknowndev** [comment]
Did you add Tectonic to an existing world?

**Comment by OfficiallyCrazy** [comment]
> Did you add Tectonic to an existing world?

Yes. Is the mod not compatible with existing worlds?

**Comment by Apollounknowndev** [comment]
Tectonic completely alters how terrain is shaped, adding it to an existing world won't end well as you can see

**Comment by OfficiallyCrazy** [comment]
Makes perfect sense. Do you suggestions on importing a small number of
chunks or an iland into a Tectonic world using something like MCA Selector?
I saw some videos saying that Minecraft 1.18 and forward had the ability to
blend previous worlds with new ones. So I thought the same could be done on
Terrain mods.
Thank your for your time
