### ISSUE TITLE
Request compatibility with The Lost Cities mod

### ISSUE THREAD

**Issue by tankyap** [Apollounknowndev/tectonic#175]
Basically the title. The worl gen is broken and its seems like its not working with [The Lost Cities mod](https://www.curseforge.com/minecraft/mc-mods/the-lost-cities), it didn't crash my game tho. (Terralith included)

[Here's the log file](https://github.com/user-attachments/files/15969240/latest.log)

When I installed The Lost Cities, and both Terralith & Tectonic, the cities basically spawns at the lower level and the Tectonic generation seems just gone, and left a bunch of floating things like glow lichens, vines or structures like this:

![Screenshot (159)](https://github.com/Apollounknowndev/tectonic/assets/87649059/2486d25f-c141-48f6-a2a2-a87f97d521f1)

![Screenshot (160)](https://github.com/Apollounknowndev/tectonic/assets/87649059/62476685-093d-4a70-94d4-0f074585d0ac)

**Comment by Apollounknowndev** [comment]
Lost Cities appears to completely ignore regular terrain shaping, even if technically fixable, it's far too much effort on an outdated version for me to bother fixing.
