### ISSUE TITLE
[Datapack] Tectonic + Terralith or Terratonic

### ISSUE THREAD

**Issue by NotSenser** [Apollounknowndev/tectonic#176]
If I use Tectonic and Terralith together as datapacks would it be the same as running Terratonic?
Currently Tectonic and Terralith have both been updated to 1.21 but Terratonic is still only available for 1.20

**Comment by Koffie9** [comment]
Any news on Terratonic 1.21 update?

**Comment by RyderGithu** [comment]
im waiting on terratonic lol. they wont work together unless you have it

**Comment by NotSenser** [comment]
I tested them both as standalone datapacks yesterday, and I assumed it worked, although some generation didn't seem right. Hoping we get an update soon

**Comment by Apollounknowndev** [comment]
Tectonic itself doesn't work with Terralith. Terratonic is a modified version of Tectonic build to run on top of Terralith. You can download the new Terratonic version [here](https://modrinth.com/datapack/terratonic/version/3.2).
