### ISSUE TITLE
hey, im playing on 1.21 fabric. tectonic world loading error

### ISSUE THREAD

**Issue by craiigee** [Apollounknowndev/tectonic#178]
im playing on 1.21 fabric with a couple of performance mods
![2024-06-30_16-34-13](https://github.com/Apollounknowndev/tectonic/assets/174256321/f677a482-c306-4a9c-83d9-77ee806c7302)
the issue that tectonic generated world turns the whole game off after 1-20 seconds after joining the world.
ive been deleting every mod one by one to try and see which makes it do that.
i also tried both datapack and mod variants of tectonic, but i thinks that they share the same problem

heres the error that minecraft laucher gives me after this:
The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null

**Comment by Apollounknowndev** [comment]
Not a Tectonic issue. Continuity is incompatible with Sodium unless you install Indium.
