### ISSUE TITLE
1.20.1  tectonic not working

### ISSUE THREAD

**Issue by Cacton12** [Apollounknowndev/tectonic#179]
I added the mod and it does not seem to change any of the world gen. I am aware it wont add new biomes but the world gen seems to be the same as normal Minecraft now I am unsure if I have another mod that conflicts with this one. I was wondering if maybe some of my structure adding mods are causing issues or if it is mod order. Any help would be great!!

**Comment by samji034p** [comment]
i got the same idk if i have to configure the mod or if it's just not working

**Comment by samji034p** [comment]
i checked more and i confirm it's working, but you have to go in a hills biome to see it.

**Comment by Apollounknowndev** [comment]
Not enough info. If this issue is still relevant please create a new issue with more details.
