### ISSUE TITLE
Cave Generation Disrupting Underground Modded Structures

### ISSUE THREAD

**Issue by connorkauff** [Apollounknowndev/tectonic#181]
Hello, I've noticed using the most recent version of Tectonic that all underground modded structures, for example from Terralith, YUNG's mods, and plenty more are extremely hard to find and not generating at their normal rates. Using the /locate command it appears structures are generating 5,000+ blocks away from any given point in the world it seems. Half the time it says there's NO structure nearby.

Is it possible to disable the custom cave generation and keep Terralith's (if they have it)/default Minecraft's? Thanks so much!

**Comment by Apollounknowndev** [comment]
Tectonic uses vanilla cave generation except for underground rivers. The broken spawn rates for underground structures may be because of a biome mod that adds a generic 'caves' biome like William Wyther's Expanded Ecosphere or Clifftree.
