### ISSUE TITLE
World height increase issues

### ISSUE THREAD

**Issue by redpid42** [Apollounknowndev/tectonic#182]
Hi. So I recently tried to increase the world height in the config (to the 640 max) and it just cuts off any terrain above y=320. Also is there  a way to make the terrain generate like up to y=500 in the settings (like changing certain values). Sorry if this is a stupid question but i can't get it to work or find help anywhere.

**Comment by saccharinesky** [comment]
i'm not sure what's going on with your first issue, maybe you disabled it on accident
answering your second question, increasing the terrain_scale modifer in the config would make terrain more extreme

**Comment by makumaku1974** [comment]
> i'm not sure what's going on with your first issue, maybe you disabled it on accident answering your second question, increasing the terrain_scale modifer in the config would make terrain more extreme

is this applicable for 1.21?

**Comment by Apollounknowndev** [comment]
Not enough info. If this issue is still relevant please create a new issue with more details.
