### ISSUE TITLE
Weird Terrain Gen

### ISSUE THREAD

**Issue by SaltSouls** [Apollounknowndev/tectonic#184]
Right now, and I can't say if this is tectonic specifically, but things like swamps, marshes, and windswept biomes have very broken and ugly terrain gen. Also, I'm not sure if it is an issue with Natures Spirit, or Terrablender, but after a while the terrain starts to look like it did back in beta. Very broken up and jagged, with floating blocks and islands. Sunken sections of land near water sources creating weird gaps. The last example image is actually a savanna biome. Again, not sure what is causing this, but is pretty jarring going from nice mountains vistas and valleys to beta terrain gen.

![01](https://github.com/Apollounknowndev/tectonic/assets/36361103/f8019eee-0d7a-4d94-a66c-53e542a19ac7)
![02](https://github.com/Apollounknowndev/tectonic/assets/36361103/cdeb306d-e85f-4eef-b165-080a63c2a508)
![03](https://github.com/Apollounknowndev/tectonic/assets/36361103/49445094-bdfb-4c66-a5f4-db8013d20ae4)
![04](https://github.com/Apollounknowndev/tectonic/assets/36361103/02825b5f-15e1-4056-879c-dbead2562228)
![05](https://github.com/Apollounknowndev/tectonic/assets/36361103/b45035ff-1855-4e47-a02f-2aa3b314fb59)
![06](https://github.com/Apollounknowndev/tectonic/assets/36361103/9c6cd52b-2f00-4e14-a705-ffcca21d07ed)
![07](https://github.com/Apollounknowndev/tectonic/assets/36361103/13a6cb89-1394-4a96-b026-538c5d24dc25)

**Comment by Apollounknowndev** [comment]
The broken terrain near water is a known issue. The windswept/Beta-like terrain is intended.
