### ISSUE TITLE
Question regarding tectonic and terralith cave generation

### ISSUE THREAD

**Issue by Killeronduty1** [Apollounknowndev/tectonic#188]
(apologies for asking this question this way I couldn't find any other way to contact you.) when using both terralith and tectonic, caves appear narrow and smaller compared to just using terralith. I wanted to know if it's possible to keep the cave generation of terralith but also include tectonic to keep the mountain ranges it forms. or if there is any way to modify the cave generation for it to be more open and large. thanks.

**Comment by Apollounknowndev** [comment]
Terralith uses the same cave generation as vanilla and Tectonic which the exception of megacaves. A future Terratonic version will have Terralith's megacaves.

**Comment by Killeronduty1** [comment]
That's great to hear I look forward to this update. keep up the great work!

**Comment by Apollounknowndev** [comment]
The update's rolled out on 1.21, backport to 1.20.1 will happen at some point.

**Comment by Kyles1201** [comment]
is it out currently

**Comment by Apollounknowndev** [comment]
Fixed in v2.4.1 for both 1.20.1 and 1.21.
