### ISSUE TITLE
possible to deactivate cave modifications by tectonic?

### ISSUE THREAD

**Issue by banan4phon3** [Apollounknowndev/tectonic#189]
maybe it's a naive question but could I maybe accomplish by deleting specific files inside tectonic, so the datapack doesn't influence cave generation, to make it compatible with alexs caves. I make datapacks myself but I'm not sure if this could very well work or completely break the whole functionallity of the datapack

**Comment by Apollounknowndev** [comment]
Tectonic doesn't impact cave generation other than adding underground rivers and removing noise cave entrances.
