### ISSUE TITLE
1.21 - impossible to generate a world using any of the superflat presets.

### ISSUE THREAD

**Issue by szymonlama** [Apollounknowndev/tectonic#190]
Hello. I tried a few times to make a superflat / empty world using the presets. However it seems like every time tectonic overrides the generation to make a regular (tectonic-ified) world instead. Is there a way to fix this without disabling the mod?

**Comment by sword-of-stabbing** [comment]
Same issue. I looked it up and found a couple issues saying it was fixed a couple versions ago, but when I use terralith and tectonic it still always makes a tectonic (terratonic? Based on what I'm seeing I think it's an issue with tectonic) world.

**Comment by sword-of-stabbing** [comment]
Ah, note that I am using terralith and tectonic as fabric mods.

**Comment by Apollounknowndev** [comment]
> Hello. I tried a few times to make a superflat / empty world using the presets. However it seems like every time tectonic overrides the generation to make a regular (tectonic-ified) world instead. Is there a way to fix this without disabling the mod?

Do you have Terralith installed? Terralith will forcefully prevent other world types from working, Tectonic can't do anything about it.
