### ISSUE TITLE
[1.19.2] Dunes in Desert biomes

### ISSUE THREAD

**Issue by 1ezekiil** [Apollounknowndev/tectonic#194]
Hello! Very love your mod, and playing with it constantly. It's so beautiful with other generation mods, like Terralith or Regions Unexplored.

So, it's isn't bug or anything else, this is more suggestion/enchancement.
Can you please add in desert biomes dunes-like generation? Terralith already have such a feature, but sadly that Tectonic don't have it.
That'll be pretty cool feature, if deserts will become more realistic, and, i think (please, don't hit me), it'll suit to the conception of Tectonic.

Thanks for your time. :з
And another one – love your mod!

**Comment by Apollounknowndev** [comment]
Tectonic... already has desert dunes???
![image](https://github.com/user-attachments/assets/685a5ca3-6e89-4270-a139-1dff0f5ad7d3)
