### ISSUE TITLE
Mod crashes entire computer suddenly, world loaded chunks in incorrect areas

### ISSUE THREAD

**Issue by OmegaRep** [Apollounknowndev/tectonic#196]
Hello Apollo, the mod I have been using is Tectonic 2.3.5b on Minecraft Java 1.20.1 on Fabric 0.15.11 Using MultiMC as my Launcher. I was playing the world with the mod just fine until suddenly my entire computer shut down. Upon rebooting Minecraft and start playing as normal I approached a village I was working in survival suddenly having chunks in the wrong areas. They were floating in the air misplaced as I also saw chunks missing. I will not be playing Minecraft or touch my world until this is fixed. Until then, could I find a way to somehow put these misplaced chunks in their correct position? I will submit two logs as they are pretty long and were split in half when the shutdown happened.

[2024-08-08-1.log.gz](https://github.com/user-attachments/files/16551465/2024-08-08-1.log.gz)
[2024-08-08-2.log.gz](https://github.com/user-attachments/files/16551466/2024-08-08-2.log.gz)

![2024-08-08_11 23 44](https://github.com/user-attachments/assets/d9959e33-26c5-4868-abd5-7b2359481653)

I will stop playing as I fear it could destroy my Minecraft builds. It fortunately only infected a small village I was barely working on and not my capital city.

**Comment by OmegaRep** [comment]
Hello everyone,

I've fixed the chunk displacement using WorldEdit's commands:

1. Hover over the trashed chunk and type `//chunk` in the Minecraft console (Its where you chat with your friends in-game). Once it's selected, type `//regen`. This will take some time to load the new chunks, even after the ping lag ends (The ping lag makes your game seem like it's frozen in time, like for example: mobs stop moving, breaking blocks stop momentarily).

This is a partial fix, and I hope Apollo and/or Team Apollo can provide a more permanent solution. I can't continuously do these commands, so I need a fix from the creator or guidance on what's causing the issue. I'll stop playing for a while and save the fixed world as a backup.

FOR MODDER(S): **Please don't close this issue yet. I require some activity or at least a comprehensive answer to close it.**

**Comment by Apollounknowndev** [comment]
Neither log file has any evidence pointing to Tectonic or any other mod causing the issue.
