### ISSUE TITLE
Minecraft world from 1.20.6 wont open after updating to 1.21

### ISSUE THREAD

**Issue by AsuzagawaAkagi** [Apollounknowndev/tectonic#197]
Tried optimizing the world, still wont open.

**Comment by Apollounknowndev** [comment]
Can you provide a log file?

**Comment by AsuzagawaAkagi** [comment]
[crash-2024-08-09_11.48.29-client.txt](https://github.com/user-attachments/files/16556354/crash-2024-08-09_11.48.29-client.txt)

**Comment by Apollounknowndev** [comment]
That's a rendering crash, not caused by Tectonic.

**Comment by AsuzagawaAkagi** [comment]
It didnt crash when I removed the mod though?
