### ISSUE TITLE
Tectonic + Geophilic doesn't blend in at times.

### ISSUE THREAD

**Issue by cobaltlol2** [Apollounknowndev/tectonic#198]
One example of this is the screenshot below, the deep and warm oceans dont mix in very well, Ill add more screenshots if I find more examples ![image](https://github.com/user-attachments/assets/41041cf1-aead-4947-8be4-e58ae9aef376)

**Comment by cobaltlol2** [comment]
Additionally, I'm not sure which mod is responsible for that, but some of the rarer biomes (jungle, mushroom fields etc) appear to generate way more than before?

**Comment by Apollounknowndev** [comment]
> One example of this is the screenshot below, the deep and warm oceans dont mix in very well, Ill add more screenshots if I find more examples

That's a rendering issue, likely with your shader. Not caused by Geophilic nor Tectonic.

**Comment by cobaltlol2** [comment]
Do you know how to make certain biomes more commont to find or rarer?
