### ISSUE TITLE
Hard to creating superflat world(mod ver)

### ISSUE THREAD

**Issue by Axc077** [Apollounknowndev/tectonic#199]
As the title said,all presets will be changed into mod's presets,it will be hard to create worlds with my own presets(espcially superflat,it's widely used).
Datapack version can solve that problem,but it's inconvenient()
If mod version is still being maintained(维护?I can't express it well),I hope it can be solved.
Two possilble examples:
      1.Add a new world type to choose
      2.Only when "default" is chosen,the mod works
Sorry for my bad English

**Comment by Axc077** [comment]
Interesting...
I walked aroud my superplat with this mod,it even worked in this map!
I created it in vanilla game and moved it to my moded game,it's really superising.I need to learn about how this mod works.
 This mod is better to just put a datapack in,I thought.

**Comment by Axc077** [comment]
My game tried to generate a village on superflat's land(edge),but the mod created new chunks with its own settings,made the village strange,as the picture.I guess the mod makes the game to generate under its settings only.
It maybe hard to rewrite the mod,but that's really inconvenient for those who use superflat to test their ideas.
![2024-08-16_17 35 44](https://github.com/user-attachments/assets/998d5772-4fdc-4337-ad90-429c41c65e20)

**Comment by Axc077** [comment]
My game cannot analyse settings of this "mixed" world23333

**Comment by Apollounknowndev** [comment]
![image](https://github.com/user-attachments/assets/ea950feb-4622-4adf-81f7-28c288648d4a)

Can't replicate. Do you happen to have Terralith installed?
