### ISSUE TITLE
Suggestion: Reduce openings to underground rivers, please.

### ISSUE THREAD

**Issue by desagas** [Apollounknowndev/tectonic#201]
Love the mod, everything looks great, except for this: 
![2024-08-18_18 02 53](https://github.com/user-attachments/assets/37c5556d-47da-4a41-afed-dde17ce1ffdd)

While I love the ambiance of the underground rivers, and can't wait to have them in my pack, it looks extremely unnatural to have the entire side of a mountain base opened up like this. It would be much better if the entrances to these were limited in diameter. They can be huge, It doesn't bother me, and the under ground river sizes are amazing when they are huge, just not the openings like this. Perhaps you can set your noise code to not break through the outer most 2 or 3 layers of blocks (stone, rock, sand, etc etc), except for entrances and random sky or side light holes?

This photo is not a unique event, it happens a lot. Using the mod with Terralith, BoP and Regions Unexplored. It is also not limited to a certain number of biomes, it happens in them, if they have taller edges, all when touching a larger river or ocean. In one case, before I decided to report on it, one of the openings on the side of a mountain was nearly 1000 blocks long. But, most around 500 or more.

On the other side, if you choose this is okay to have, I would suggest a compromise: perhaps the outer most layers outside are guaranteed to have pillar supports every so often, with the original material from the generator, and since you already have this in your code for generation inside of the underground rivers, with the support columns every so often, I assume it would not be hard to adapt it to the outer most layers, exposed to the outside?

Anyways, just my suggestion.

**Comment by desagas** [comment]
This one is perfect, and ones like this: 
![2024-08-18_18 34 31](https://github.com/user-attachments/assets/53b33cca-004a-415c-83e3-9cb97cdf6870)

But there are more like the first: 
![2024-08-18_19 19 50](https://github.com/user-attachments/assets/5677019a-beed-4f0b-8e82-0448f75973bb)
 
Actually, I really love this cove. You see, while this one is borderline good/too wide, if the distance it inset into the edge was only maybe 20 or 30 blocks, and then flowed into a much bigger underground river, OR if the pillars on the outside of the river were holding it up, where they are missing, this would look amazing, with an overhang like that, but the way it is now, it is almost too much, imo.

This one accomplishes what I mentioned, with only about a 30 block inset, and the it enters into more underground, and then I digress, as flying around, it was not as common a problem as I initially thought: 
![2024-08-18_19 24 38](https://github.com/user-attachments/assets/eb244c3d-700a-4888-bafb-5dbfc18a9ca3)

**Comment by Axc077** [comment]
The first picture is too mad.How can it be generated...23333

**Comment by Apollounknowndev** [comment]
While I would like to fix it, it's not really possible to do so. There's no "max entrance width" to configure; Underground rivers simply carve out where rivers would be near mountains and sometimes that can be at strange angles.

**Comment by desagas** [comment]
Ah, I see. Then I agree with other commenters: it would be better if there was a config to turn off the underground rivers.

It can be fixed, just might take a little bit of innovation or new code.

**Comment by Apollounknowndev** [comment]
Underground rivers are toggleable in the config file.
