### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by cyivert** [Apollounknowndev/tectonic#210]
![image](https://github.com/user-attachments/assets/52e781ce-7dfd-4aee-bf17-3c04ad4470fe)

I want to know if this is a bug or so; I have downloaded the proper version of the tectonic plate for 1.21.1 it crashes my SMP due to this cause I am not quite sure what is the full detail of the cause.

**Comment by Apollounknowndev** [comment]
That isn't a crash, just a harmless warning. If you're crashing, it's because of other reasons.
