### ISSUE TITLE
Parsing error loading recipe

### ISSUE THREAD

**Issue by Kishku7** [Apollounknowndev/tectonic#211]
I'm getting this error on both my server and my local client.
I've disabled all other worldgen mods, in fact left only the basic libraries.

To Reproduce:
Modrinth + Tectonic 2.4.1a + Lithosticed

Once game is loaded, click single player, and select New World, error shows in logs on Modrinth.

Sample:
[14:46:50] [Render thread/ERROR]:
Parsing error loading recipe quark:world/crafting/woodsets/blossom/trapdoor
at MC/net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader.java:13) ~[client-intermediary.jar:?]
com.google.gson.JsonParseException: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: quark:blossom_trapdoor; Map entry '#' : Failed to parse either. 
First: Input does not contain a key [fabric:type]: MapLike[{"item":"quark:blossom_planks"}]; 
Second: Failed to parse either. First: Not a json array: {"item":"quark:blossom_planks"}; 
Second: No key tag in MapLike[{"item":"quark:blossom_planks"}]; 
Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: quark:blossom_planks
 
This error fills the logs with a multitude of errors.

Note that the error log happens before the world is actually created. On the server where there is already a world, the error happens on Start.

**Comment by Apollounknowndev** [comment]
That is a Quark recipe error, has nothing to do with Tectonic or Lithostitched at all.
