### ISSUE TITLE
Mountains getting cut off above y=320 with increased_height setting

### ISSUE THREAD

**Issue by KB-Q** [Apollounknowndev/tectonic#219]
What it says in the title. Attached screenshot for reference.

Minecraft version: 1.20.1
Mod version: 2.4.1

full mods list: https://paste.ee/p/BhevD

![image](https://github.com/user-attachments/assets/4e0f0926-6f33-4e53-8cf9-b0a24fd5a343)

**Comment by Apollounknowndev** [comment]
Can't replicate on a fresh Terralith + Tectonic instance so it's likely a conflict with a third mod.

![image](https://github.com/user-attachments/assets/abd5b604-e702-468f-947c-f31c55abb468)

**Comment by Apollounknowndev** [comment]
Only occurs on Fabric.

**Comment by Apollounknowndev** [comment]
Fixed in v2.4.2, releasing soon.
