### ISSUE TITLE
Crash with Arclight 1.20.1 (Trials/1.0.5)

### ISSUE THREAD

**Issue by jsmoctezuma** [Apollounknowndev/tectonic#225]
[2024-09-25-1.log](https://github.com/user-attachments/files/17130138/2024-09-25-1.log)
[crafttweaker.log](https://github.com/user-attachments/files/17130139/crafttweaker.log)
[crash-2024-09-25_06.29.34-server.txt](https://github.com/user-attachments/files/17130140/crash-2024-09-25_06.29.34-server.txt)
[debug-1.log](https://github.com/user-attachments/files/17130141/debug-1.log)

server crashes generating new chunks

**Comment by Apollounknowndev** [comment]
Looks like an Arclight or a Bukkit issue with another mod's custom structure type, so not a Tectonic issue.
