### ISSUE TITLE
Issues with superflat worlds (1.21 ver.)

### ISSUE THREAD

**Issue by KyoshuGD** [Apollounknowndev/tectonic#228]
Whenever I try to create a superflat world with the mod enabled, it ends up with normal world generation. A more jarring issue is the fact that new chunks in pre-existing superflat worlds end up with regular generation, which led to a void world I had poured hours into having a deep cold ocean surrounding everything.

**Comment by KyoshuGD** [comment]
found out it's an issue with worldgen mods in general (at least on my end) after testing Terralith as well

**Comment by Apollounknowndev** [comment]
This is specifically a Terralith issue. This shouldn't occur with Tectonic on its own.

**Comment by KyoshuGD** [comment]
my bad, I'll do more testing next time
