### ISSUE TITLE
Suggestion: World Border

### ISSUE THREAD

**Issue by Chowbox87** [Apollounknowndev/tectonic#234]
Maybe not the best place to leave it but I love this mod and its generation so here we go!

My idea is a sort of world border, maybe something in a config, maybe a server config, that lets you determine a certain rectangular world size, and a second smaller border in which tectonic begins to attempt to form an ocean. Say it is 10,000 blocks for the outermost border, and 9,000 for the inner. 

The goal is to create an ocean border around the world, to combine with world wrapping features from mods like immersive portals in order to make a navigable “globe” in Minecraft. If this is beyond the scope of this project, no offense taken I already appreciate so much what yall do. Feel free to get rid of this thread if it’s annoying

**Comment by Apollounknowndev** [comment]
This is an interesting idea I'll probably explore at some point, but not for Tectonic. It'd likely be its own thing.
