### ISSUE TITLE
compatibility issue with the mod "blueprint"

### ISSUE THREAD

**Issue by Grant-Silliman** [Apollounknowndev/tectonic#235]
Blueprint by teamAbnormals overrides the terrain generation of tectonic making it vanilla generation.

**Comment by Apollounknowndev** [comment]
Can you give a mod list?

**Comment by Grant-Silliman** [comment]
- adlods 8.1.3.0
	- amendments 1.20-1.2.11
	- angelring 2.2.1
	- apotheosis 7.4.3
	- apothic_amendments__enchanting 0.1.4
	- apothic_sups_enchanting 0.1.2
	- apothiccombat 1.1.0
	- apothiccurios 1.0.3d
	- appleskin 2.5.1+mc1.20.1
	- aquaculture 2.5.2
	- architectury 9.2.14
	- ars_creo 4.1.0
	- ars_elemental 1.20.1-0.6.7
	- ars_nouveau 4.12.4
	- artifacts 9.5.13
		\-- expandability 9.0.4
	- athena 3.1.2
	- attributeslib 1.3.7
	- auroras 1.4.1
	- balm 7.3.9
		\-- kuma_api 20.1.8
	- beautify 2.0.2
	- bettercombat 1.8.6+1.20.1
	- betterdeserttemples 1.20-Forge-3.0.3
	- betterdungeons 1.20-Forge-4.0.4
	- betterfortresses 1.20-Forge-2.0.6
	- betterjungletemples 1.20-Forge-2.0.5
	- bettermineshafts 1.20-Forge-4.0.4
	- betteroceanmonuments 1.20-Forge-3.0.4
	- betterstrongholds 1.20-Forge-4.0.3
	- betterthirdperson 1.9.0
	- betterwitchhuts 1.20-Forge-3.0.3
	- biomemusic 1.20.1-2.5
	- biomesoplenty 18.0.0.592
	- biomeswevegone 1.3.1
	- bookshelf 20.2.13
	- botanypots 13.0.39
	- botanypotstiers 6.0.1
	- botanytrees 9.0.17
	- bountiful 6.0.3+1.20.1
	- brandonscore 3.2.1.302
	- buildinggadgets2 1.0.7
	- caelus 3.2.0+1.20.1
	- chipped 3.0.6
	- citadel 2.6.0
	- cloth_config 11.1.136
	- clumps 12.0.0.4
	- codechickenlib 4.4.0.516
	- cofh_core 11.0.2
	- commonnetworking 1.0.5-1.20.1
	- constructionwand 1.20.1-2.11
	- controlling 12.0.2
	- cookingforblockheads 16.0.9
	- corgilib 4.0.3.2
	- crafting_on_a_stick 1.1.5
	- craftingtweaks 18.2.5
	- create 0.5.1.i
		\-- flywheel 0.6.11-13
	- create_eureka 1.0.0+forge-1.20.1
	- createaddition 1.20.1-1.2.4e
	- createdeco 2.0.2-1.20.1-forge
	- createoreexcavation 1.5.2
	- creeperoverhaul 3.0.2
	- ctov 3.4.9b
	- cucumber 7.0.12
	- cupboard 1.20.1-2.7
	- curios 5.10.0+1.20.1
	- curiotiab 1.20.1-2.0.2
	- cyclic 1.12.13
	- darkutils 17.0.5
	- deeperdarker 1.3.2
	- design_decor 0.4.0b
	- dimdungeons 194
	- draconicevolution 3.1.2.588
	- dungeoncrawl 2.3.14
	- dungeons_arise 2.1.58-1.20.x
	- easy_villagers 1.20.1-1.1.23
	- embeddium 0.3.31+mc1.20.1
		\-- rubidium 0.7.1
	- endermanoverhaul 1.0.4
	- endrem 5.3.3-R-1.20.1
	- extradisks 1.20.1-3.0.2
	- farmingforblockheads 14.0.2
	- ferritecore 6.0.1
	- flib 0.0.14
	- forge 47.3.0
	- forgeendertech 11.1.4.0
	- framedblocks 9.3.1
	- framework 0.7.8
	- ftbchunks 2001.3.1
	- ftbessentials 2001.2.2
	- ftblibrary 2001.2.4
	- ftbteams 2001.3.0
	- ftbultimine 2001.1.5
	- fusion 1.1.1
	- gateways 4.2.6
	- geckolib 4.4.9
	- handcrafted 3.0.6
	- hostilenetworks 5.3.1
	- industrialforegoing 3.5.17
	- inventoryessentials 8.2.6
	- jade 11.11.1+forge
	- jadeaddons 5.3.1+forge
	- jei 15.20.0.104
	- jeresources 1.4.0.247
	- journeymap 5.10.3
	- justenoughprofessions 3.0.1
	- justzoom 2.0.0
	- kambrik 6.1.1+1.20.1
	- konkrete 1.8.0
	- kotlinforforge 4.11.0
	- leavesbegone 8.0.0
	- library_of_exile 1.5.2
	- lithostitched 1.3.0
	- lootr 0.7.34.87
	- luphieclutteredmod 2.1
	- majruszlibrary 7.0.8
	- majruszsaccessories 1.5.3
	- majruszsdifficulty 1.9.10
	- medieval_buildings 1.0.2
	- medievalend 1.0.1
	- mes 1.3.1-1.20-forge
	- minecraft 1.20.1
	- mob_grinding_utils 1.20.1-1.1.0
	- modernfix 5.19.4+mc1.20.1
	- modularrouters 12.1.1+mc1.20.1
	- moonlight 1.20-2.13.7
		\-- mixinextras 0.3.6
	- moremobvariants 1.3.0.1
	- mousetweaks 2.25.1
	- mysticalagradditions 7.0.4
	- mysticalagriculture 7.0.14
	- naturescompass 1.20.1-1.11.2-forge
	- octolib 0.4.2
	- oculus 1.7.0
	- ohthetreesyoullgrow 1.20.1-1.3.1
	- overflowingbars 8.0.1
	- patchouli 1.20.1-84-FORGE
	- pickupnotifier 8.0.0
	- pigpen 15.0.2
	- pipez 1.20.1-1.2.16
	- placebo 8.6.2
	- playeranimator 1.0.2-rc1+1.20
	- polymorph 0.49.5+1.20.1
		\-- spectrelib 0.13.15+1.20.1
	- powah 5.0.7
	- productivebees 1.20.1-12.6.0
	- productivetrees 1.20.1-0.2.6
		\-- productivelib 1.20.1-0.0.4
	- puzzleslib 8.1.24
		\-- puzzlesaccessapi 8.0.7
	- pylons 4.2.1
	- quark 4.0-460
	- quarkoddities 1.20.1
	- rebornstorage 5.0.7
	- refinedpolymorph 0.1.1-1.20.1
	- refinedstorage 1.12.4
	- refinedstorageaddons 0.10.0
	- refurbished_furniture 1.0.6
	- regions_unexplored 0.5.6
	- relics 0.8.0.7
	- reliquary 2.0.44.1243
	- repurposed_structures 7.1.15+1.20.1-forge
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.29
	- rsinfinitybooster 1.20.1-1.0+39
	- rsinsertexportupgrade 1.20.1-1.4.0
	- rsrequestify 2.3.3
	- runelic 18.0.2
	- searchables 1.0.3
	- shrink 1.4.5
	- silentcompat 1.4.0
	- silentgear 3.6.6
	- silentgems 4.7.0
	- silentlib 8.0.0
	- simplemagnets 1.1.11
	- simplyswords 1.56.0-1.20.1
	- sophisticatedbackpacks 3.20.11.1115
	- sophisticatedcore 0.6.34.718
	- sophisticatedstorage 0.10.45.912
	- spark 1.10.53
	- structory 1.3.5
	- structory_towers 1.0.7
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.17+a
	- supplementaries 1.20-2.8.17
		\-- mixinsquared 0.1.1
	- tectonic 2.4.1
	- terrablender 3.0.1.7
	- terralith 2.5.4
	- thermal_cultivation 11.0.1
	- thermal_dynamics 11.0.1
	- thermal_expansion 11.0.1
	- thermal_foundation 11.0.6
		\-- thermal 11.0.6
	- thermal_innovation 11.0.1
	- thermal_integration 11.0.1
	- thermal_locomotion 11.0.1
	- tiab 4.0.4-mc1.20.1
	- titanium 3.8.32
	- tlc 1.0.2
	- torchmaster 20.1.8
	- unusualend 2.1.0
	- valkyrienskies 2.3.0-beta.5
	- vs_clockwork 1.20.1-0.1.16-forge-b3b22e39fe
	- vs_eureka 1.5.1-beta.3
	- waystones 14.1.5
	- yungsapi 1.20-Forge-4.0.6
	- yungsbridges 1.20-Forge-4.0.3
	- yungscavebiomes 1.20.1-Forge-2.0.1
	- yungsextras 1.20-Forge-4.0.3
	- zeta 1.0-24



I was trying to use mod "the outer end" and it uses blueprint as a dependency. thats when i noticed the issue and removed those mods.

**Comment by Apollounknowndev** [comment]
Tried just blueprint, outer end and tectonic and it worked fine. Some other mod must be causing an issue.
![image](https://github.com/user-attachments/assets/d8351717-d803-4ad4-abf1-2f1b9ee994d9)

**Comment by Grant-Silliman** [comment]
Thanks for your time with this. I think I was being dumb honestly. with having so many biome mods I convinced myself that it wasn't generating correctly. I just added the mod back. your mod is great.
