### ISSUE TITLE
Increased World Height

### ISSUE THREAD

**Issue by mike23564** [Apollounknowndev/tectonic#236]
I can't seem to get the increased height setting to work, I'm using the latest 1.20.1 forge version of the mod on my curseforge modpack and in finding mountains and building up it all stops at 320, created another test modpack with only tectonic installed and it does the same, some guidance in this would be helpful, not sure if the setting straight up doesn't work yet or if I'm inputting the config wrong, changed it from false to true so let me know if I did something wrong there

**Comment by mike23564** [comment]
Sorry nevermind, apparently the chage wasn't saving in the config file

**Comment by XEpicLi** [comment]
lmao close the issue then bro
