### ISSUE TITLE
Increased world height doesn't affect generation

### ISSUE THREAD

**Issue by glorification12** [Apollounknowndev/tectonic#237]
forge 1.20.1, tectonic 2.3.5a.

I looked into the other issues and mine is not similar. where others have their generation literally cut off at >320, my world doesn't even generate up to that. I know the config is working because I can build above 320 to exactly 640, but the world generation simply doesn't reach there. I tested in my default config settings for all world scalings, and amongst the ~10 mountainous biomes I check there was none above 320. When I made another test world and bumped the verticality scaling up to 1.4, no terrain generated above 320, however one structure sitting on top of a mountain managed to make it to 340. 

Other than tectonic, I have terralith, create, BWG, RU, noisium, and farmers delight for worldgen.

**Comment by Apollounknowndev** [comment]
Try a vertical scale of 1.8 or so.

**Comment by glorification12** [comment]
Worked, thank you
