### ISSUE TITLE
Is there a way to fix Village generation?

### ISSUE THREAD

**Issue by segoitch** [Apollounknowndev/tectonic#241]
![grafik](https://github.com/user-attachments/assets/21fc2ab1-4da1-4b66-b895-d5efb19bfb42)

**Comment by Apollounknowndev** [comment]
Vanilla issue, can't fix.

**Comment by segoitch** [comment]
> Vanilla issue, can't fix.

Isn't that why mods exist?

**Comment by Apollounknowndev** [comment]
Fixing it requires implementing height difference-based checks for structures. This isn't in the scope of Tectonic.
