### ISSUE TITLE
Better Andesite Distribution For Create?

### ISSUE THREAD

**Issue by Gantros** [Apollounknowndev/tectonic#244]
I use Create. I like Tectonic. While I appreciate being able to turn off underground rivers and such, it’s very difficult to find andesite without the benefit of a mod like Terralith, which adds dedicated stone cave biomes. Could you add a config option or datapack that incorporates andesite more plentifully into worldgen?

**Comment by Apollounknowndev** [comment]
Not in the scope of Tectonic.
