### ISSUE TITLE
Terralith Volcanic Crater biome does not generate with Tectonic

### ISSUE THREAD

**Issue by Veffers** [Apollounknowndev/tectonic#245]
When using both terralith and tectonic the volcanic crater biome (the biome that is the center of terralith volcanos) does not generate and you end up with just the volcanic peaks biome. I believe this has to do with how terralith volcanos generate with the volcanic crater biome only generating if surrounded by volcanic peaks biome but tectonic's mountain ranges messes this up somehow.

**Comment by Apollounknowndev** [comment]
Known quirk of Terratonic, not fixable without basically rewriting terrain shaping.
