### ISSUE TITLE
Tectonic compatible with Deeper Oceans?

### ISSUE THREAD

**Issue by LughtMon** [Apollounknowndev/tectonic#246]
Hello, I want to use Tectonic to make flatter areas with sometimes occuring huge mountains. but making the surface flat also flatterns the oceans, which are now too shallow. I have added another mod "Deeper Oceans" but it seems to do nothing. Is there another way or am I doing something wrong?

**Comment by emihead** [comment]
You may have noticed this already, but in case you haven't, Tectonic has its own Deeper Oceans feature in the config.

**Comment by LughtMon** [comment]
> You may have noticed this already, but in case you haven't, Tectonic has its own Deeper Oceans feature in the config.

Oh, yea that's enabled but oceans are still too shallow, max 15 blocks deep. it changed because I set this:     "terrain_scale": 0.2
Don't know what to do as the terrain in the oceans will be affected too by this config.

**Comment by Apollounknowndev** [comment]
There's really nothing you can do at such a low terrain scale, the terrain is basically a pancake at that point.

**Comment by LughtMon** [comment]
> There's really nothing you can do at such a low terrain scale, the terrain is basically a pancake at that point. Deeper Oceans and Tectonic aren't compatible as Tectonic has all of Deeper Ocean's features.

I get it, but is there som way how to exclude oceans from this config I have set? Or some other mod, which can overerite tectonic oceans?
