### ISSUE TITLE
Evergreen Forest Has Trees On Top Of Trees

### ISSUE THREAD

**Issue by Rebel459** [Apollounknowndev/tectonic#25]
Not sure if it's because of terralith (both mod versions), but tectonic's evergreen forest has birch trees spawning on top of birch trees on top of birch trees (with a singular dirt block where the tree was planted/spawned

**Comment by Rebel459** [comment]
Didn't seem to occurr in a pre-existing world in a different pack, will need to do more testing

**Comment by Rebel459** [comment]
Definitely not Terralith's fault, both mods work fine together in my modpack. In my other instance, however, every regular Evergreen Forest has the issue

**Comment by Rebel459** [comment]
The issue is on every instance of this specific pack, which I will attach a zip for here with all relevant files
[Tectonic Evergreen Forest Bug Test 1.19.2.zip](https://github.com/ApolloDatapacks/tectonic/files/11392922/Tectonic.Evergreen.Forest.Bug.Test.1.19.2.zip)

**Comment by Rebel459** [comment]
Haven't checked vanilla, but hopefully this helps :)

**Comment by ApolloDatapacks** [comment]
Can you provide a list of mods you have installed? The pack you have sent doesn't seem to be recognized as an actual modpack on MultiMC. This is definitely a conflict with another mod as I cannot replicate this on an instance without any other mods.

**Comment by Rebel459** [comment]
Sorry, did the CF format as GitHub wouldn’t accept a mrpack attachment. The list of mods, all latest versions as of initially writing this (1.19.2 fabric compatible) were Additional Additions, Diamond Nuggets, Entity Culling, Farmer’s Delight, Farmer’s Knives, Iris Shaders, LazyDFU, Lithium, Oxidized, Paxi, Polymorph, Sodium, Tectonic, Terralith and YUNG’s API. It should also be noted that many, if not all of those mods were present in my other, larger instance (not all latest version though) with no issue.

**Comment by SpudGunMcGee** [comment]
<details>
<summary>Screenshots</summary>
<img src="https://i.vgy.me/KZk8kt.png"> 
<img src = "https://i.vgy.me/nfxWu4.png">
</details>

<details open>
<summary>Modlist</summary>
<a href="https://moddermore.net/list/beafa42c13">https://moddermore.net/list/beafa42c13</a>

Experiencing the same issue here, minecraft version 1.19.2, forge 43.2.10. Mod list is as above.

**Comment by SpudGunMcGee** [comment]
Looking at the mod versions, I see that the version of Terralith I have installed is v2.3.7b which seems to specify that it is for 1.19.3 specifically. I'm using PRISM and is does not seem to distinguish the difference between versions. Downgrading Terralith to v2.3.5 seems to fix the issue with my quick initial test

**Comment by SpudGunMcGee** [comment]
Just tested with a new instance with just Tectonic v1.1.10 and Terralith v2.3.7b installed and this seems to still be happening. Interestingly for me, this only seems to happen in the birch forest biome specifically and not in the evergreen biome as @Rebel459 describes.

**Comment by Rebel459** [comment]
I have the latest versions of Tectonic and Terralith together in a completely seperate and pretty large 1.19.2 Fabric pack with no issue, so there’s definitely something strange going on here.

**Comment by SpudGunMcGee** [comment]
What is EXTRA odd is that I just tested this on fabric and got the exact same issue

[https://i.vgy.me/WVG5Yv.png](url)

**Comment by SpudGunMcGee** [comment]
This issue was introduced in v1.1.10. Downgrading to the previous version 1.1.9b seems to fix the issue until the bug is addressed. @Rebel459. I imagine this has to do with the removal of custom tectonic tree generation.

**Comment by Rebel459** [comment]
Again, I don’t have the issue in v1.1.10 in my modpack, only a smaller one I used for testing

**Comment by LunarPidgeon** [comment]
Experiencing this issue as well.

**Comment by Jaximo98-dev** [comment]
Same issue here. Vanilla birch forest affected if Terralith and Tectonic are enabled.

**Comment by Jaximo98-dev** [comment]
> Again, I don’t have the issue in v1.1.10 in my modpack, only a smaller one I used for testing

I managed to reproduce incompatibility if Tectonic is in 1.1.10... Seems like there is still some code messing with tree generation.

**Comment by Apollounknowndev** [comment]
Fixed in v2, will be closed once Tectonic v2.1 for 1.18.2 releases.

**Comment by Apollounknowndev** [comment]
Fixed in v2, which is (finally) out for all versions.
