### ISSUE TITLE
Crashes on latest release when using a boat (Fabric)

### ISSUE THREAD

**Issue by WatermelonOfTheSea** [Apollounknowndev/tectonic#256]
I was playing for a while without any issues, but after I used a boat, the game froze, then crashed. It didn't give me a crash log, (I'm using the normal Minecraft launcher), but it did give me exit code -1073741819 if that helps any. Tectonic is the only mod other than Iris and Fabric

**Comment by Apollounknowndev** [comment]
This isn't a Tectonic issue, it is a file system error that may be caused by some other computer function.
