### ISSUE TITLE
Strange chunk block breaks in the world

### ISSUE THREAD

**Issue by ncottrill** [Apollounknowndev/tectonic#258]
In the newest version, the terrain, particularly mountains, often generate with strange cuts that look like they are just cut along chunk borders. It almost looks as if part of the terrain wasn't generated - like, there appear to be chunk-sized holes.

**Comment by ncottrill** [comment]
Example image 
![image](https://github.com/user-attachments/assets/d38d6fdc-57ee-472a-a5de-89cb5dd25744)

**Comment by Apollounknowndev** [comment]
Vanilla quirk of terrain shaping around windswept biomes.
![image](https://github.com/user-attachments/assets/a8b4dbc0-3cd6-4a20-a258-ebc8b825773c)
