### ISSUE TITLE
Config to turn off everything but rivers

### ISSUE THREAD

**Issue by TylerButh** [Apollounknowndev/tectonic#265]
I like the Terralith biomes and mountain shapes but I want the tectonic rivers that cut through the mountain. So I'd like to be able to turn everything off except the rivers.

**Comment by TylerButh** [comment]
If there is a public repo somewhere maybe I can add it myself?

**Comment by TylerButh** [comment]
Actually I see there is an underground rivers mod by you... maybe that is already what I'm looking for...

**Comment by Apollounknowndev** [comment]
The [Underground Rivers](https://modrinth.com/mod/underground-rivers) mod exists for this exact purpose :P
