### ISSUE TITLE
Incompatibility?

### ISSUE THREAD

**Issue by AnimatedGlitch** [Apollounknowndev/tectonic#266]
When I add any world generation altering mod on top of Tectonic, It breaks the world generation making it so that worlds like super flat just don't generate.
I've noticed this when combining Tectonic with mods like Cliff under a tree and V-PaleGarden.

Any explanation or solution would be greatly appreciated.

**Comment by Apollounknowndev** [comment]
These aren't compatibility issues, other world types won't work when using Clifftree or V-Pale Garden on their own.
