### ISSUE TITLE
Incompatible with Cave Enhancements

### ISSUE THREAD

**Issue by Rebel459** [Apollounknowndev/tectonic#27]
Title. Cave Enhancements' caves to not generate when used with Tectonic (its 1 structure works fine)

**Comment by Rebel459** [comment]
also incompatible with Mushroom Additions' caves

**Comment by Apollounknowndev** [comment]
There is nothing Tectonic v2 can do to resolve the issue. This is an issue due to how both mods add their biomes to the overworld biome layout. 
Tectonic v2 does not have the issue at all.
