### ISSUE TITLE
Tick Lag Issue

### ISSUE THREAD

**Issue by MythrilBagels** [Apollounknowndev/tectonic#29]
I've been getting some unfortunate overcrowded-server-like tick lag while playing with this mod in Singleplayer. Mobs will often rubber band, making combat borderline unfair. I tried using the same instance without the mod, with vanilla terrain generation, and the issue was not present. I also tried the mod on its own, and the issue was still present, albeit less noticeable.

Unrelated, but I recall seeing in the changelog that the custom trees were removed due to unsolvable lag issues. Was that frame lag or tick lag?
Also, theoretically, would you consider reimplementing the custom trees if the lag issues were not present? They were my favourite feature of the mod and it is truly upsetting to see them gone (They actually made forests enjoyable to traverse and made swamps actually pretty.)
I know it was suggested to use other tree-based mods, but this one used to tickle my fancy just right. That, and I feel other mods tend to go overboard in my opinion

**Comment by Apollounknowndev** [comment]
I really can't do anything about the lag. I've optimized Tectonic as much as I really can, but it's still somewhat performance intensive.
In regards to the trees, I intend on bringing them back as a Not Just Biomes module. The version of them in Tectonic were very laggy as I had to use a hack to make them work, but the performance impact of them will disappear once implemented in an actual mod.

**Comment by MythrilBagels** [comment]
Oh thats great to hear! I'll keep an eye out for it then.
Also I slightly exaggerated a bit, its not "overcrowded-server" level tick lag, its more akin to that of a server thats been running for a bit without restarting.
Small price to pay for good world-gen
