### ISSUE TITLE
Birch forests are messed up when running Tectonic and Terralith together

### ISSUE THREAD

**Issue by arovium** [Apollounknowndev/tectonic#30]
Trees in Birch forests generate on top of one another when using Tectonic (1.19.2-v1.1.10) and Terralith (v2.3.8) together. I'm using Minecraft version 1.19.2 on Forge.

![2023-06-16_14 09 05](https://github.com/Apollounknowndev/tectonic/assets/122307248/bcd1a53c-a5f1-4135-9b8c-252aed2462fe)
![2023-06-15_16 48 09](https://github.com/Apollounknowndev/tectonic/assets/122307248/250c3570-b13f-4d35-98a5-53209c162ed7)

**Comment by Apollounknowndev** [comment]
Known issue (See #25)
