### ISSUE TITLE
Treasure maps spawn as empty maps called "Buried Treasure Maps"

### ISSUE THREAD

**Issue by ClaudioHidalgo03** [Apollounknowndev/tectonic#31]
I've found three of these maps in shipwrecks playing on 1.20.1

**Comment by Apollounknowndev** [comment]
Vanilla issue, see [MC-249136](https://bugs.mojang.com/browse/MC-249136).

**Comment by NixityNull** [comment]
I have had this same problem repeatedly with every treasure map i come across in fabric 1.21.1 So i think this datapack may be causing the vanilla bug to happen consistently
