### ISSUE TITLE
Tectonic seems to change biome weighting

### ISSUE THREAD

**Issue by glorification12** [Apollounknowndev/tectonic#32]
running a forge 1.19.2 mod pack with Tectonic, Terralith, BYG, and BOP. For some reason, as soon as I add Tectonic the biome weighting gets heavily skewed toward vanilla biomes. What I mean is that around 60-70% of the found biomes are vanilla whereas when I remove tectonic around 20% are vanilla biomes. Is this a compatibility issue with BYG and BOP or plenty that I'm not noticing or could it be something else? Any help is appreciated.

**Comment by Apollounknowndev** [comment]
I wasn't ever to replicate this issue or find people who did have the issue, and it would have been fixed in v2 anyways.
