### ISSUE TITLE
Built in Terratonic not performing as expected with Terralith. (1.18.2)

### ISSUE THREAD

**Issue by cayenne-cep** [Apollounknowndev/tectonic#33]
Hi, I've had an issue with the Terratonic datapack (https://www.planetminecraft.com/data-pack/terratonic/), detailed here Apollounknowndev/pack-library#1. The issue strangely doesn't exist in the mod version. 

However, a new issue has cropped up, in that Terralith biomes don't seem to be generating? 

Here's a screenshot of two diff instances, one using both the Tectonic & Terralith mod.
![2023-06-22_06 30 37](https://github.com/Apollounknowndev/tectonic/assets/41793769/00bad729-d8f5-4c90-a26e-51bbce50aa78)

The other using the datapack versions.
![2023-06-22_06 28 38](https://github.com/Apollounknowndev/tectonic/assets/41793769/fe76d5bb-9b46-487d-a97c-1bbe3ff524c0)

These are the same coords, and seem to be the same landforms, minus whatever Terralith is suppose to be doing in the modded ver.

<details><summary>Modlist</summary>
<p>

	- cloth-config 6.3.81
	   \-- cloth-basic-math 0.6.1
	- cristellib 1.0.0
	   \-- blue_endless_jankson 1.2.1
	- fabric-api 0.76.0+1.18.2
	   |-- fabric-api-base 0.4.5+64b7c69360
	   |-- fabric-api-lookup-api-v1 1.6.3+2373a54560
	   |-- fabric-biome-api-v1 8.0.7+e83becad60
	   |-- fabric-block-api-v1 1.0.0+ee3621fc60
	   |-- fabric-blockrenderlayer-v1 1.1.13+3ac43d9560
	   |-- fabric-command-api-v1 1.1.10+d7c144a860
	   |-- fabric-commands-v0 0.2.9+b4f4f6cd60
	   |-- fabric-containers-v0 0.1.24+d7c144a860
	   |-- fabric-content-registries-v0 3.1.3+c85f2e3860
	   |-- fabric-convention-tags-v1 1.1.0+43ce63a460
	   |-- fabric-crash-report-info-v1 0.2.1+ee261a3e60
	   |-- fabric-data-generation-api-v1 3.1.0+6c70b68e60
	   |-- fabric-dimensions-v1 2.1.21+489d6f8260
	   |-- fabric-entity-events-v1 1.4.9+d7c144a860
	   |-- fabric-events-interaction-v0 0.4.20+d7c144a860
	   |-- fabric-events-lifecycle-v0 0.2.22+d7c144a860
	   |-- fabric-game-rule-api-v1 1.0.13+d7c144a860
	   |-- fabric-item-api-v1 1.6.2+8165403660
	   |-- fabric-item-groups-v0 0.3.16+91896a4960
	   |-- fabric-key-binding-api-v1 1.0.12+54e5b2ec60
	   |-- fabric-keybindings-v0 0.2.10+b4f4f6cd60
	   |-- fabric-lifecycle-events-v1 2.1.1+cc71601c60
	   |-- fabric-loot-api-v2 1.1.2+1997ad1260
	   |-- fabric-loot-tables-v1 1.1.4+e747827960
	   |-- fabric-mining-level-api-v1 2.1.6+cc71601c60
	   |-- fabric-models-v0 0.3.7+d7c144a860
	   |-- fabric-networking-api-v1 1.0.24+2d30af4b60
	   |-- fabric-networking-v0 0.3.11+b4f4f6cd60
	   |-- fabric-object-builder-api-v1 2.1.5+032c981d60
	   |-- fabric-particles-v1 0.2.13+526dc1ac60
	   |-- fabric-registry-sync-v0 0.9.12+bb2e047760
	   |-- fabric-renderer-api-v1 0.5.0+bf48649860
	   |-- fabric-renderer-indigo 0.6.1+03e2b68760
	   |-- fabric-renderer-registries-v1 3.2.12+b4f4f6cd60
	   |-- fabric-rendering-data-attachment-v1 0.3.9+ee3621fc60
	   |-- fabric-rendering-fluids-v1 2.0.3+54e5b2ec60
	   |-- fabric-rendering-v0 1.1.14+b4f4f6cd60
	   |-- fabric-rendering-v1 1.10.8+54e5b2ec60
	   |-- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660
	   |-- fabric-resource-loader-v0 0.5.3+047a5ecb60
	   |-- fabric-screen-api-v1 1.0.11+d882b91560
	   |-- fabric-screen-handler-api-v1 1.2.3+1f6558e860
	   |-- fabric-textures-v0 1.0.13+3ac43d9560
	   |-- fabric-transfer-api-v1 1.6.4+f4563ac860
	   \-- fabric-transitive-access-wideners-v1 1.1.0+e747827960
	- fabricloader 0.14.19
	- java 17
	- minecraft 1.18.2
	- modmenu 3.2.5
	- seedfix 1.0.1
	- tectonic 1.1.10a
	- unfixed-seeds 1.0.2

</p>
</details>

**Comment by cayenne-cep** [comment]
I should also mention I can't /locate Terralith biomes, at least the ones I tried (about 4-5 of them). So, they don't seem to be generating anywhere.

**Comment by Apollounknowndev** [comment]
Terratonic isn't built into Tectonic 1.18.2. I ran into issues with both Forge and Fabric that prevented me from just doing a direct port.

**Comment by cayenne-cep** [comment]
Shoot sorry I didn't realize. Unfortunately, that puts me back to square one with the Terratonic issue I already mentioned.

**Comment by ChosenMoren** [comment]
1.19.4 version of both mods work?

**Comment by Apollounknowndev** [comment]
Yes, this is specifically an issue with 1.18.2.

**Comment by Apollounknowndev** [comment]
Fixed in v2, which is (finally) out for all versions.
