### ISSUE TITLE
Please add a config or something so that we can customize the world biomes or height or depth

### ISSUE THREAD

**Issue by ALPHAGAMER42** [Apollounknowndev/tectonic#34]

**Comment by ALPHAGAMER42** [comment]
Feature request

**Comment by ChoiceTheorem** [comment]
Great feature requests should contain the following:
- A clear and concise description of the feature. What are you requesting? What would it do? How would it work?
- An explanation of the problem the feature would solve. Why do you need this feature? What problem would it solve for you or other users?
- A use case or example of how the feature would be used. This will help the developer understand how the part would fit into their mod and how it would be used by real users.
- Any relevant screenshots or videos that illustrate your request. This can be helpful for the developer to understand your request and how it would work.

Here are some additional tips for writing a good feature request:

- Be specific. The more specific you can be about the feature you are asking for, the better. The product team will be more likely to understand your request and be able to prioritize it.
- Be clear about the problem you are trying to solve. The product team needs to understand why you need this feature and how it would benefit users.
- Be realistic. Don't request features that are too complex or that would require a lot of development time. The product team needs to be able to prioritize features based on their feasibility.
- Be respectful. Remember that the product team is working hard to create a great product. Be respectful of their time and effort when you submit a feature request.
Modified from Google Bard response.

**Comment by Apollounknowndev** [comment]
Not currently planned, and will likely not be in the future. That would require hacking in a config for what is internally just a datapack, and I don't want to do that.

**Comment by Villanueva-Flavio** [comment]
Can we just recompile our own version if that's so? what kind of variables should we look to?
btw i'm sorry to reopen the issue, but, im eager to help :D
