### ISSUE TITLE
add a way to stop the underground rivers from making really ugly terrain 

### ISSUE THREAD

**Issue by Thefatsparrow** [Apollounknowndev/tectonic#36]
maybe add pillars or something to stop terrain looking ugly. it just does not look right with the rest of the really smooth terrain

![image](https://github.com/Apollounknowndev/tectonic/assets/86117177/e236c593-ccc2-48fe-8cbf-37d0cf3d06b4)

**Comment by Apollounknowndev** [comment]
Not planned at the moment. I've attempted fixes but they've lead to other greater issues.

**Comment by Thefatsparrow** [comment]
ahh alright thanks

**Comment by QuentinLeCaignec** [comment]
I absolutely understand that this might be very difficult to fix without creating other problems. From the little I understand of how you're handling rivers to transform them into underground rivers it looks hard to integrate smoothly at the entrances/exits like this.

But I have to agree, it's the only aspect of the terrain generation that I would consider to be a downside, this and some instances of cliff generation can be very jarring, either making weirdly flat, "slice" looking cutoff to the terrain, or cliffs looking like they bit off a portion of the terrain but with leftovers hanging in the air.

In any case what this mod is already impressive and must have been a lot of work, so thanks.

Is there anything specific that is preventing this improvement, a way to possibly fix this in the future?
