### ISSUE TITLE
Compatible with Regions Unexplored?

### ISSUE THREAD

**Issue by Samapoke** [Apollounknowndev/tectonic#37]
Everytime I tried to locate one of your biome, it will say "Could not find a biome of type "Tectonic's biome" within reasonable distance."
Is it because of other biome mod? I also used Regions Unexplored.

**Comment by Apollounknowndev** [comment]
Tectonic biomes don't generate in Tectonic v2, but the biomes cannot be removed from the files or else old worlds will corrupt.

**Comment by Samapoke** [comment]
> Tectonic biomes don't generate in Tectonic v2, but the biomes cannot be removed from the files or else old worlds will corrupt.

Thank you for explanation.
