### ISSUE TITLE
Doesn't respects the superflat preset

### ISSUE THREAD

**Issue by SamuelUlep** [Apollounknowndev/tectonic#38]
Creating a new world in any other preset sure the world generation does what I want it to do, but when I try making a super flat world to test something out, it ignores the superflat preset and instead creates a world as if it was set to default world gen.

I'm using the mod version btw in conjunction with terralith. I have tested it with either of the mods to see if its just one of them causing problems but both mods cause a similar issue.

**Comment by SamuelUlep** [comment]
It seems like you are aware of the [issue](https://bugs.mojang.com/browse/MC-260949) and so does Stardust the author of Terralith of the limitation Minecraft imposes with regards to world generation, I'll keep this thread open until I get confirmation from @Apollounknowndev about the issue being known.

**Comment by Apollounknowndev** [comment]
In Tectonic specifically, this issue _can_ be fixed. Planned for a future release.

**Comment by Apollounknowndev** [comment]
Fixed in Tectonic v2.1 mod version. Datapack version won't be getting this fix due to technical issues.

**Comment by SamuelUlep** [comment]
> Fixed in Tectonic v2.1 mod version. Datapack version won't be getting this fix due to technical issues.

Thanks for the fix
