### ISSUE TITLE
[Question] Need to remove changes that make ocean deeper.

### ISSUE THREAD

**Issue by murao-kun** [Apollounknowndev/tectonic#39]
Is there any way to undo deeper ocean changes? (On 2.0)

**Comment by Thefatsparrow** [comment]
i know i want to aswell half the time its a massive drop and half the time its too deep

**Comment by Apollounknowndev** [comment]
Open `data/minecraft/worldgen/density_function/overworld/offset.json`

In the file, go to lines 54, and 59. Change the values in each from -0.45 to -0.22.
