### ISSUE TITLE
Compatibility with Continents mod

### ISSUE THREAD

**Issue by QuentinLeCaignec** [Apollounknowndev/tectonic#40]
This mod is absolutely fantastic, especially when combined with Terralith.

However I've been trying to make it work with the Continents mod as well. Continents works with Terralith, but it seems like Tectonic/Terratonic overrides its settings.

I'm using the mod versions of Terralith, Terratonic and Continents.

I've started tinkering with datapack files to edit stuff for myself, but I'm not sure how to do this. Is there a way to retain continents settings, or to reach a similar result with tectonic, ie. having actual distinct islands and continents surrounded by large oceans ?

**Comment by Apollounknowndev** [comment]
Fixed in v2.1.1.
