### ISSUE TITLE
Small ponds are broken in swamps and other bodies of water 1.20.1

### ISSUE THREAD

**Issue by ghost** [Apollounknowndev/tectonic#46]
in the swamp biome
and also in caves where there are ponds with water, water flows out in a place where it should not flow out, thereby flooding everything around
the same is observed with lava

used mods
tectonic-mod-mc1.19.3+-v2.1 and fabric-api-0.86.1+1.20.1
![2023-08-05_21 02 18](https://github.com/Apollounknowndev/tectonic/assets/80956290/e8318a27-f076-4bd8-8ef0-5a7fb17ba8b8)
![2023-08-05_21 02 20](https://github.com/Apollounknowndev/tectonic/assets/80956290/fa5ed156-65c1-4ead-a7eb-419f401fedd3)
![2023-08-05_21 02 28](https://github.com/Apollounknowndev/tectonic/assets/80956290/890c33d2-df8c-4afe-9950-95eeb2438f84)
![2023-08-05_21 02 33](https://github.com/Apollounknowndev/tectonic/assets/80956290/e0fe50ed-35ee-4f00-9006-42a1c0b502b0)
![2023-08-05_21 02 34](https://github.com/Apollounknowndev/tectonic/assets/80956290/ed29c467-ff15-4b22-998a-8ab954fde550)
![2023-08-05_21 02 39](https://github.com/Apollounknowndev/tectonic/assets/80956290/a295eb8e-5e34-4e8d-a3bd-80fe48ea63fa)
![2023-08-05_21 02 41](https://github.com/Apollounknowndev/tectonic/assets/80956290/5c8feaf2-870c-49ea-b191-2afd30d4c960)
![2023-08-05_21 02 46](https://github.com/Apollounknowndev/tectonic/assets/80956290/7bff364d-ee03-4dfa-8ba9-baee35eb10f8)
![2023-08-05_21 02 47](https://github.com/Apollounknowndev/tectonic/assets/80956290/a138a36d-c471-4fee-8cb5-293fe0981b93)
![2023-08-05_21 02 49](https://github.com/Apollounknowndev/tectonic/assets/80956290/fae0026a-041b-4119-aebd-2f18be78510a)
![2023-08-05_21 02 53](https://github.com/Apollounknowndev/tectonic/assets/80956290/6c34251b-3b83-4508-bc96-44b459cc2f9d)
![2023-08-05_21 02 59](https://github.com/Apollounknowndev/tectonic/assets/80956290/174ce85d-a278-467d-912d-1253d760853e)

**Comment by HollowedWanderer** [comment]
Yeah I'm having the same problem, I'm trying to mess around with some of the datapack files to see if I can fix it. I'll let you know if I get anything working.

**Comment by HollowedWanderer** [comment]
ok.. so I sort of found a solution. I completely removed the original water feature using the noise settings for the swamp biome and making it impossible for it to spawn. Then I created a new feature that was extremely similar to the lava deltas in the nether. However I used mud as a rim and water as the filler. This ended up creating a similar effect to what was originally intended

**Comment by Apollounknowndev** [comment]
Should be fixed in v2.1.1.
