### ISSUE TITLE
Passive Mob Spawning Rate

### ISSUE THREAD

**Issue by aNinjin** [Apollounknowndev/tectonic#47]
**Minecraft Version:** _1.20.1_
**Tectonic Version:** _v2.1_
**Forge:** _47.1.1_

I was running into an issue where passive mobs seemed to be super rare and would only spawn in either one's or two's. I'm talking no cows, pigs, chickens, and sheep's for hundreds of blocks. I started troubleshooting the mod pack I was creating by disabling and recreating worlds. Once I created a world without Tectonics, passive mob spawns went back to their normal numbers.

Is this supposed to be a feature?

**Comment by Apollounknowndev** [comment]
I have not been able to replicate this issue, on an instance with nothing except Tectonic mob spawns function fine. Perhaps this is a mod conflict?

**Comment by aNinjin** [comment]
> I have not been able to replicate this issue, on an instance with nothing except Tectonic mob spawns function fine. Perhaps this is a mod conflict?

Hmmm, let me start removing WG mods and see which one is the culprit. I will report my findings.
