### ISSUE TITLE
Disables 1.18+ Cave Generation (V2.1 1.19.2)

### ISSUE THREAD

**Issue by VlRlON** [Apollounknowndev/tectonic#50]
New cave generation seems to be disabled when using Tectonic v2.1 for 1.19.2. I tested the same seed and coordinates every time (6881264172110781008 @ 133 -4 -519 if you'd like to test the same one yourself). Once Tectonic was enabled the large cavern did not generate. Any large caverns only seemed to be the result of Quark.
I tested this in vanilla Minecraft and the same issue happened, so it doesn't seem to be a mod conflict.  All testing used Forge v43.2.21 and the mod version of Tectonic.

[with Tectonic](https://github.com/Apollounknowndev/tectonic/assets/142056403/bf02de1c-ff81-43c8-8054-ce713362bd2a)
[without Tectonic](https://github.com/Apollounknowndev/tectonic/assets/142056403/001af449-5bd7-4962-9064-aca24390977b)

I have never used Github before and made this account just to create this issue, so I apologize if the images are broken!

**Comment by Apollounknowndev** [comment]
Working as intended. Tectonic introduces a completely different cave generation system, which means Tectonic and vanilla caves do not align.

**Comment by ghosty141** [comment]
> Working as intended. Tectonic introduces a completely different cave generation system, which means Tectonic and vanilla caves do not align.

Hi, sorry for being kinda late but I was wondering, does tectonic actually have a completely custom cave system or does it use pre-1.18 cave logic? How much work would it be to port the new cave generation over? I might take a look if it's not a herculean effeort.

**Comment by Apollounknowndev** [comment]
My information was for an older version of Tectonic. Tectonic v2.1 and above use vanilla cave generation.

**Comment by ghosty141** [comment]
Oh great, thanks for the quick reply!
