### ISSUE TITLE
1.20.1 Terratonic + Terralith, missing volcanic crater + caldera biomes

### ISSUE THREAD

**Issue by loftoxos** [Apollounknowndev/tectonic#52]
Could not locate [_terralith:volcanic_crater_](https://stardustlabs.miraheze.org/wiki/Volcanic_crater) or [_terralith:caldera_](https://stardustlabs.miraheze.org/wiki/Caldera) local world across 50k blocks. Similar result when testing across several seeds on jacobsju's [datapack map](https://map.jacobsjo.eu/). 

Tested with Terralith 2.4.3 and Terratonic 3.0.1 on 1.20.1.

**Comment by Apollounknowndev** [comment]
This is due to those biomes only spawning inside mountain rings normally. Biomes inside mountain rings don't generate with Tectonic because mountain rings don't exist. If I find a way to reimplement the biomes I will, but for now it's not something I'm looking into.

**Comment by Kyles1201** [comment]
woah this would be very cool to have the volcanoes on terratonic!
