### ISSUE TITLE
Mountain biomes plateau in large biomes 1.20.1

### ISSUE THREAD

**Issue by ChunkyMonkey54** [Apollounknowndev/tectonic#54]
Fabric 1.20.1 0.14.22
Tectonic 2.1

Mountain biomes do not have the same jaggedness as they do in the default world type. I can't confirm this second part but they also seem to generally be smaller and struggle to form proper mountain ranges.

All the pictures below are the different peak biomes which should be the most jagged.

![2023-09-09_15 46 29](https://github.com/Apollounknowndev/tectonic/assets/28323717/e4b5b2bf-abc2-4cbc-a81e-2cb88e783a8d)

![2023-09-09_15 46 49](https://github.com/Apollounknowndev/tectonic/assets/28323717/b727ffff-e2d6-426f-9ff5-7b10b91f5ca9)

![2023-09-09_15 48 48](https://github.com/Apollounknowndev/tectonic/assets/28323717/544141dc-d5f1-4fd3-825e-a2f1bb85995c)

**Comment by Apollounknowndev** [comment]
Fixed in v2.1.1.
