### ISSUE TITLE
Broken beaches 1.20.1

### ISSUE THREAD

**Issue by ChunkyMonkey54** [Apollounknowndev/tectonic#55]
Fabric 1.20.1 0.14.22
Tectonic 2.1

Beach biome seem to sometimes slope below sea level causing water to flow in and create an overall messy appearance. This issue is greatly exacerbated in large biome worlds. It also happens in snowy beaches. This also seems to create some weird islands.
![2023-09-09_15 33 10](https://github.com/Apollounknowndev/tectonic/assets/28323717/72a5c7d3-60f8-4bd4-b7c4-dfd885416d50)
![2023-09-09_15 38 49](https://github.com/Apollounknowndev/tectonic/assets/28323717/d2d85fe5-0763-43c0-9bfe-6230ed874bd9)
![2023-09-09_15 41 18](https://github.com/Apollounknowndev/tectonic/assets/28323717/43731dcc-2bf6-4dc1-9b1d-d91902af3e2f)
![2023-09-09_15 42 11](https://github.com/Apollounknowndev/tectonic/assets/28323717/daae53f7-e8b6-461f-af64-f11255d5a668)
![2023-09-09_15 43 00](https://github.com/Apollounknowndev/tectonic/assets/28323717/2e2f7220-3a58-4454-b667-8fbd2058bcea)
![2023-09-09_15 43 20](https://github.com/Apollounknowndev/tectonic/assets/28323717/2d3e2100-18cc-447f-a768-09ed80f35008)

**Comment by Apollounknowndev** [comment]
Should be fixed in v2.1.1.

**Comment by SaltSouls** [comment]
I'm not suite sure this has been 100% fixed.
![2023-11-04_20 01 16](https://github.com/Apollounknowndev/tectonic/assets/36361103/35cee394-5d31-4a0e-bcdb-c5cd76b6fa56)
![2023-11-04_20 02 23](https://github.com/Apollounknowndev/tectonic/assets/36361103/9cf5f850-acf4-4a75-a649-6d45444491cd)
![2023-11-04_20 02 34](https://github.com/Apollounknowndev/tectonic/assets/36361103/6f96dc1c-2a85-4069-b747-fba6d1e9e4d8)
Here is my [mod/datapack list](https://gist.github.com/SaltSouls/7356d238404f0bf8186e49e81f2db09d) in case this may be a compatibility issue.

**Comment by Apollounknowndev** [comment]
> I'm not suite sure this has been 100% fixed. ![2023-11-04_20 01 16](https://user-images.githubusercontent.com/36361103/280503712-35cee394-5d31-4a0e-bcdb-c5cd76b6fa56.png) ![2023-11-04_20 02 23](https://user-images.githubusercontent.com/36361103/280503715-9cf5f850-acf4-4a75-a649-6d45444491cd.png) ![2023-11-04_20 02 34](https://user-images.githubusercontent.com/36361103/280503716-6f96dc1c-2a85-4069-b747-fba6d1e9e4d8.png) Here is my [mod/datapack list](https://gist.github.com/SaltSouls/7356d238404f0bf8186e49e81f2db09d) in case this may be a compatibility issue.

This is a compat issue with Cliffs and Coves, can't fix.

**Comment by SaltSouls** [comment]
> This is a compat issue with Cliffs and Coves, can't fix.

Thanks, I'll report this to the datapack creator.
