### ISSUE TITLE
[1.20.1] Tropicraft Compatibility

### ISSUE THREAD

**Issue by HerrBeef** [Apollounknowndev/tectonic#58]
Hi,

it seems like Tropicraft and Tectonic are not compatible in 1.20.1 with Forge 47.2.1
When i install Tectonic and Tropicraft i can't go in to the tropics anymore, the Tropics can't be generated.
Could it be that Tectonic tries to modify how the terrain is generated in the tropics? I don't have this problem with other world generation / biome adding mods (biomes o plenty, regions unexplored, structure generation mods like yungs, structory etc)

**Comment by SanguineWaters** [comment]
Can confirm it does not work in 1.21 as well when trying to enter the tropic dimension.
Versions
- tectonic-neoforge-1.21-2.4.0.jar 
- neoforge-21.0.95-beta-universal.jar 
- Tropicraft-9.7.1.jar
- client-1.21-20240613.152323-srg.jar
[crash-2024-07-21_17.50.44-server.txt](https://github.com/user-attachments/files/16326286/crash-2024-07-21_17.50.44-server.txt)

**Comment by Apollounknowndev** [comment]
Fixed in a future release for 1.21. A backport of the fix to pre-1.21 may happen at some point but can't necessarily promise it.

![image](https://github.com/user-attachments/assets/9fb176a0-fa92-4938-bacc-0074ef0c49f0)

**Comment by Apollounknowndev** [comment]
Fixed in v2.4.1 for both 1.20.1 and 1.21.
