### ISSUE TITLE
Terralith Ancient Sands

### ISSUE THREAD

**Issue by Answordy** [Apollounknowndev/tectonic#59]
I'm not sure if it is intentional but using Terralith and Tectonic (mod versions) together replaces the sand dunes with mountains and large flat fields in ancient sand, desert and probably some other biomes that have them. It doesnt look bad it just doesnt really fit.

![2023-10-08_12 43 44](https://github.com/Apollounknowndev/tectonic/assets/82783515/b35ac1d7-2586-4cc8-be0d-f15ba79b6e82)
![2023-10-08_12 44 06](https://github.com/Apollounknowndev/tectonic/assets/82783515/1a999c58-753d-49bc-8bb6-d86ec6e1e80c)
![2023-10-08_13 19 51](https://github.com/Apollounknowndev/tectonic/assets/82783515/7fe78159-55e2-4bc0-b032-16c79ce883ab)
![2023-10-08_13 20 13](https://github.com/Apollounknowndev/tectonic/assets/82783515/aa020aea-b068-4ccf-b376-4c063889a395)

Latest 1.19.2 Terralith and Tectonic versions

**Comment by Apollounknowndev** [comment]
Similar generation happens in default Terralith, so this won't be fixed.
(Source: [Terralith wiki page on Ancient Sands](https://stardustlabs.miraheze.org/wiki/Ancient_sands))
![2021-12-18_18 56 49](https://github.com/Apollounknowndev/tectonic/assets/102649729/742a5142-f380-4d29-b4b2-692d5f51e3c5)
