### ISSUE TITLE
Possibly too much Ancient Cities spawn

### ISSUE THREAD

**Issue by Answordy** [Apollounknowndev/tectonic#60]
This is on 1.19.2, the picture was taken in a modded environment, however I did test it in vanilla as well. Though im not familiar with ancient city spawns so sorry if it is intended or normal behavior.
![2023-10-08_19 57 27](https://github.com/Apollounknowndev/tectonic/assets/82783515/c0f34092-ec14-43ac-82b1-6026e8820181)

**Comment by Apollounknowndev** [comment]
Ancient Cities in vanilla tend to generate clustered together because their placement is roughly based on the mountainous terrain on the surface. Tectonic amplifies this further due to mountain ranges, but it's ultimately caused by vanilla.
