### ISSUE TITLE
Superflat unavailable with mod ?

### ISSUE THREAD

**Issue by hamer51** [Apollounknowndev/tectonic#61]
hi i was making a modpack and found when i went to go make a superflat for some testing and it still generates as tectonic terrain y=-64 bedrock , rivers , and all . And when i saw no like wise issues open or closed i figured i should report it to yall

**Comment by Apollounknowndev** [comment]
Which pack version?

**Comment by hamer51** [comment]
the version is : 
tectonic-mod-mc1.19.3+-v2.1.1.jar

**Comment by hamer51** [comment]
not used to using github sorry not trying to close this

**Comment by Apollounknowndev** [comment]
Open `tectonic.json` in the config folder of your instance. Is `compatible_mode` enabled?

**Comment by hamer51** [comment]
"legacy_mode" is the only thing showing up in that file and it says its set to false atm should i switch that to true ?

**Comment by Apollounknowndev** [comment]
Are you using Terralith?

**Comment by hamer51** [comment]
yes

**Comment by Apollounknowndev** [comment]
Terralith issue, can't be fixed due to a vanilla bug.
