### ISSUE TITLE
[1.18.2 Forge] The world generation is the exact same no matter the seed

### ISSUE THREAD

**Issue by Y1rd** [Apollounknowndev/tectonic#62]
Using v2.1.1a Datapack, no matter what seed is put in, using the datapack will result in the same world generation regardless of the seed. Trees, structures and such are different, however the general terrain is always the same. It will always the player ontop of a mountain, with a valley in front and a large lake with a island in it.
![2023-10-09_22 41 31](https://github.com/Apollounknowndev/tectonic/assets/100542617/148a1b3b-3861-480b-9ff1-3a65d9f60fca)

**Comment by Apollounknowndev** [comment]
Vanilla bug that was patched in 1.19. If on Fabric, use [Unfixed Seeds](https://modrinth.com/mod/unfixed-seeds).

**Comment by Y1rd** [comment]
Know anything for forge perhaps?

**Comment by Apollounknowndev** [comment]
Ah, need to add Forge's native fix. Reopening.

**Comment by Y1rd** [comment]
Fixed as of v2.1.1b. Issue no longer happens on Forge. Thanks!
Also you didn't seem to close this issue, so I'll just do that.
