### ISSUE TITLE
[1.19.2] Broken landscapes

### ISSUE THREAD

**Issue by lunanium** [Apollounknowndev/tectonic#63]
Hi. I often come across broken landscapes.

There are no mods affecting the generation of the world.

**Comment by lunanium** [comment]
![2023-10-12_12 30 21](https://github.com/Apollounknowndev/tectonic/assets/134201789/b920f796-0feb-48aa-9225-5e7dd20b019a)

![2023-10-12_02 52 39](https://github.com/Apollounknowndev/tectonic/assets/134201789/a457d543-4ec2-49f2-8934-21f616eadfdb)

**Comment by Apollounknowndev** [comment]
That's [windswept savanna](https://minecraft.wiki/w/Savanna#Windswept_Savanna) terrain. It's a thing in vanilla, it's a thing in Tectonic.
