### ISSUE TITLE
[Terratonic v3 1.20.1] Some Terralith biomes don't generate as they are supposed to

### ISSUE THREAD

**Issue by Bablela26** [Apollounknowndev/tectonic#65]
Some Terralith biomes that have special features don't generate properly :
Haze mountain, Jungle mountains, Stony spires and Desert spires are flat most of the time.
(here a Haze mountain on the left and a Stony spires on the right)
![image](https://github.com/Apollounknowndev/tectonic/assets/80642972/5fde5e25-2637-463b-a1d4-73688970679a)

I know of Issue #52 that mountain rings don't generate, also that cliff biomes (Basalt cliffs, Frozen cliffs, Granite cliffs and White cliffs) can't generate either.

**Comment by Kyles1201** [comment]
plz fix

**Comment by ultimatejacob27** [comment]
I will add to this that the glacial chasm doesn't generate properly, especially that the giant ice spikes don't appear at all

**Comment by Apollounknowndev** [comment]
Mostly fixed in a future release. 
![image](https://github.com/user-attachments/assets/5f35b738-785f-4dfe-99ad-88da72a4a95d)

**Comment by Apollounknowndev** [comment]
Fixed in v2.4.1 for both 1.20.1 and 1.21.
