### ISSUE TITLE
Updated release?

### ISSUE THREAD

**Issue by BiddinWar** [Apollounknowndev/tectonic#67]
Trying to install this for 1.20.2 but 
- I can't see a version listed here for it 
- the one listed on curseforge only has the .jar files and no .zip 
Am I missing something obvious here or what? Asking as I'm using Paper, and per your [Server FAQ](https://github.com/Apollounknowndev/tectonic/wiki/FAQ#server-faq) I should grab the .zip but as mentioned above, the one available on github is v1.1.3 (mc 1.19)

**Comment by Apollounknowndev** [comment]
Curseforge only holds the mod version, as a datapack version would need a separate page and it would get messy. You can download the datapack version from [Modrinth](https://modrinth.com/datapack/tectonic)

**Comment by BiddinWar** [comment]
I see, thanks a lot o/
