### ISSUE TITLE
crashes on forge

### ISSUE THREAD

**Issue by Ectopekk** [Apollounknowndev/tectonic#71]
i can get to the title screen but when i try to start a world i get "The game crashed whilst mouseclicked event handler
Error: net.minecraftforge.fml.ModLoadingException: Tectonic (tectonic) encountered an error during the done event phase"

im not sure what this means but i have the crash report https://pastebin.com/YNQ0EWgV

**Comment by CtrldChaos101** [comment]
I also have this issue, it happens as soon as pressing "Single Player"

**Comment by Apollounknowndev** [comment]
1.20.2 is no longer a supported version and I cannot replicate this on any other version.
