### ISSUE TITLE
Snow at biome borders

### ISSUE THREAD

**Issue by KostromDan** [Apollounknowndev/tectonic#72]
Looks a little wired.
![image](https://github.com/Apollounknowndev/tectonic/assets/90044015/1582c96b-7edb-4beb-b9fd-ae65a6b74a75)
![image](https://github.com/Apollounknowndev/tectonic/assets/90044015/912a887a-b5f3-43cd-91a2-0deeb27f319c)
Reproduction:
M-Tech modpack 1.19.2 1.7.3
1. Install tectonic
2. seed 1903054364403993938
3. /execute in minecraft:overworld run tp 385.79 119.13 686.50

**Comment by Apollounknowndev** [comment]
Cannot be fixed normally without overriding the Stony Shore biome and leading to compatibility issues. Fixed in v2.2.1 if you have the Lithostitched mod installed.
