### ISSUE TITLE
Snow generation on the trees.

### ISSUE THREAD

**Issue by KostromDan** [Apollounknowndev/tectonic#73]
![image](https://github.com/Apollounknowndev/tectonic/assets/90044015/930270a3-bfa1-4c97-9c87-165555d2bfa7)
If tree is in one chunk, and leaves in another, snow won't generate on others chunk part.

**Comment by Apollounknowndev** [comment]
This is a vanilla bug that's existed for a long white. The [Simple Snowy Fix](https://modrinth.com/mod/simple-snowy-fix) mod fixes it.

**Comment by KostromDan** [comment]
> This is a vanilla bug that's existed for a long while. The [Simple Snowy Fix](https://modrinth.com/mod/simple-snowy-fix) mod fixes it.

Any fix for forge?

**Comment by Apollounknowndev** [comment]
No equivalent fix for Forge.

**Comment by KostromDan** [comment]
Ported to forge and neo
https://github.com/KostromDan/Simple-Snowy-Fix
