### ISSUE TITLE
Ocean Monument Generation

### ISSUE THREAD

**Issue by pancakeofsin** [Apollounknowndev/tectonic#74]
Version 1.20.1, both datapack and mod

I'm loving the super deep oceans, except every single ocean monument generates **2 blocks below sea level** -- which makes for a really cool looking monument, but the cool factor kind of wears off once you realise that's how all of them look -- is there any way to add height variation for the structure generation?
![2023-12-16_01 41 38](https://github.com/Apollounknowndev/tectonic/assets/149578036/1b74796c-781f-456a-b35c-d8a0106b419a)
![2023-12-16_01 46 31](https://github.com/Apollounknowndev/tectonic/assets/149578036/cf63f8ef-4a6b-46cc-8d48-01be60eb07b6)

**Comment by Apollounknowndev** [comment]
Can't fix, ocean monument height is hardcoded.

**Comment by pancakeofsin** [comment]
oh my god, it is. i was *so* sure that they spawn at varying heights, i was about to call bullshit, but i checked because that would be both rude and very embarrassing if i was wrong. and i am. how have i never noticed before???

i think i will decrease monument generation to preserve the wow effect they give off the first time you find one to counteract how silly they look if theres multiple within one render distance :P 

thanks for a timely and concise response!

**Comment by NolanHewitt** [comment]
While this doesn't fix the issue, you could try using Yung's better ocean monuments mod. I find they look really nice with tectonics deeper oceans.
