### ISSUE TITLE
1.20.1 Forge crash w/ Terralith

### ISSUE THREAD

**Issue by Apollounknowndev** [Apollounknowndev/tectonic#77]
Initially reported by a user in Stardust Labs.
https://api.mclo.gs/1/raw/esnY7W2

**Comment by mccalltristan** [comment]
I fixed this by going into datapacks and putting Terratonic above Terralith. For some reason it defaulted to below it. Now I load into a world with no crashes.

**Comment by Apollounknowndev** [comment]
Not this issue again >:/

Thanks for the info, fix should hopefully come soon provided I find how to fix the issue

**Comment by Plasman888** [comment]
How would I change the order of them when I'm using the mod version of each

**Comment by Apollounknowndev** [comment]
Can't replicate the issue.
