### ISSUE TITLE
v2.2 crashes on Quilt 1.18.2

### ISSUE THREAD

**Issue by HugoIsNotACoder** [Apollounknowndev/tectonic#81]
Minecraft is crashing when i launch since updating to 2.2 in 1.18.2, tried running with no other mods but unfixed seeds and quilt api, but no luck. 

Crash report -> https://pastebin.com/Lfm7f9CG

**Comment by Apollounknowndev** [comment]
Looks like a Quilt-specific issue, will look into it

**Comment by NolanHewitt** [comment]
It doesn't crash for me on Quilt, but it does break superflat generation.

**Comment by Apollounknowndev** [comment]
1.18.2 is no longer a supported version.
