### ISSUE TITLE
1.20.1 How to control biome size

### ISSUE THREAD

**Issue by gabuly** [Apollounknowndev/tectonic#83]
Hi! Really liked the mod, its so unique for terrain mods in 1.20.  The biomes look great but is there anyway to limit the size of certain biomes like forests? I have limited knowledge about mod making so I have done a lot of searching trying to make biomes smaller by changing the noise settings in the datapack but it doesnt work. Please let me know if there is anyway to customized it even a direction is helping :)

**Comment by Apollounknowndev** [comment]
I'd recommend asking in `#worldgen-dev` in the [Stardust Labs](https://discord.gg/stardustlabs) discord, as this is more of a general worldgen question than a Tectonic-specific question.
