### ISSUE TITLE
Terratonic V3.1 generates a huge number of oceanside cliffs (in several biomes)

### ISSUE THREAD

**Issue by Lordphiphi** [Apollounknowndev/tectonic#86]
I'm not sure if it's a bug, but it feels like one: Terratonic generates a lot of oceanside cliffs, I know it's a Tectonic feature, but they're everywhere, not just in the stony shore biome. If that's not a bug, then I would suggest to reduce their number.

**Datapacks :** Terralith 2.4.11, Terratonic 3.1 _|_ **Seed :** 1373515187657802518 _|_ **Location :** /execute in minecraft:overworld run tp @s 348.64 95.46 511.41 28.13 9.75

In any case, I've just discovered Tectonic and it's an incredible datapack, congratulations to the devs!

![image](https://github.com/Apollounknowndev/tectonic/assets/126831463/2c3a0313-8ffd-4a54-ac4e-fa42c72752ca)
![image](https://github.com/Apollounknowndev/tectonic/assets/126831463/838548f8-ad42-4297-9411-9694c8db2100)
![image](https://github.com/Apollounknowndev/tectonic/assets/126831463/81e3e3a3-6c8b-4d4a-8050-04c4b806b1a1)

**Comment by grugsy** [comment]
I was thinking the same thing (just with more mods in my case) but was focused on the other issue first. 
![2024-01-29_00 29 22](https://github.com/Apollounknowndev/tectonic/assets/6725027/2fc29018-ec32-46a7-8bd8-108cc2ae40d7)
![2024-01-29_00 29 54](https://github.com/Apollounknowndev/tectonic/assets/6725027/6dbcdbe0-705a-4cd5-89de-744c72b7f7c8)

**Comment by virtualsaturn** [comment]
I noticed this too. At the very least something to stop sandy beaches from spawning on top of cliffs would be nice since that placement makes 0 sense even for Minecraft.

**Comment by BarteG44** [comment]
Same issue for me

![2024-02-14_00 05 33](https://github.com/Apollounknowndev/tectonic/assets/105491762/63286742-74d0-418b-8c2e-4f1193e4cdd5)

cliffs themselves wouldn't be too bad but it looks like they're all made by pretty much just cutting out spheres out of the shore, including making a dent in the seafloor which just sticks out so much

**Comment by Apollounknowndev** [comment]
The generation of the cliffs outside the Stony Shore is due to Terralith messing with the biome placement and it's not really something I can fix. However, I have made two changes in v2.2.1 that should help mitigate issues:
- Cliffs won't dig in as deep into the terrain as they did before
- Around 60% of the time, cliffs will not generate at all.

![image](https://github.com/Apollounknowndev/tectonic/assets/102649729/a83bd990-0cbd-4cd4-b4ba-3b984e5b6499)
