### ISSUE TITLE
Chunk Generation Biome Error When updating to 2.2 from 2.1.1

### ISSUE THREAD

**Issue by GrandAlbert** [Apollounknowndev/tectonic#87]
![2024-01-22_18 12 30](https://github.com/Apollounknowndev/tectonic/assets/60528176/7980bdde-9aca-4bcb-ad68-63b73b315e34)
When I updated to 2.2 from 2.1.1 this happened to my oceans, warm oceans right next to deep frozen oceans. This happens everywhere now and only happened to me when I updated to 2.2 from 2.1.1, even if I go back to 2.1.1 this still happens how did this happen and what do I do to fix it? 
This is in 1.19.2 btw

**Comment by NolanHewitt** [comment]
Version 2.2 breaks stuff, its best to avoid version 2.2 and use the previous version until an updated version which fixes the issue is released

**Comment by Apollounknowndev** [comment]
If you're going back to 2.1.1 and the issue still persists, it's because the world seed changed which is completely out of Tectonic's control.
