### ISSUE TITLE
invalid discord invite link on Modrinth

### ISSUE THREAD

**Issue by gxnda** [Apollounknowndev/tectonic#88]
I'm assuming this is maintained by this same team, but the [invite link](https://discord.gg/vFz67Pvceu) on the [Modrinth page](https://modrinth.com/datapack/tectonic) is invalid.

**Comment by Edrow-6** [comment]
I think the discord server has been deleted because I was removed from the server a few days ago.

**Comment by Apollounknowndev** [comment]
Issue with all discord links, will be fixing over the next few weeks.
