### ISSUE TITLE
Unable to update map from 1.19.2 to 1.20.1

### ISSUE THREAD

**Issue by Krachboomman** [Apollounknowndev/tectonic#89]
Hello.
I am unable to load my world after updating my game to 1.20.1. As far as I am able to understand the log, it seems that the game wont register tectonic the same way it did in 1.19.2.
Is there any way to fix this or am I stuck on version 1.19.2?

[latest.log](https://github.com/Apollounknowndev/tectonic/files/14074298/latest.log)

**Comment by NolanHewitt** [comment]
If youre using version 2.2 of the mod its because that version breaks world generation is a few ways currently. I'd recommend trying the version released before 2.2 and see if that fixes the issue for you.

**Comment by Apollounknowndev** [comment]
Follow the instructions in #48 and the issue should be fixed.

**Comment by Krachboomman** [comment]
> Follow the instructions in #48 and the issue should be fixed.

Thx very much for the help!
