### ISSUE TITLE
Tectonic, Terratonic, and other biome mods: A 1.19.2 story.

### ISSUE THREAD

**Issue by grugsy** [Apollounknowndev/tectonic#90]
When using terratonic on quilt alongside several other biome mods and continents, weird behavior happens where mushroom biomes/variants and deep/cold oceans generate together. It generates the surface as at the seafloor level instead of where it should be and fills it in like an ocean. Structures still spawn at surface level, everything else is as it should be... except underground... because the surface is now the bottom and borks the underground gen it "should" line up with. 
![missing](https://github.com/Apollounknowndev/tectonic/assets/6725027/4eaac094-cf57-4053-811c-48a2db4c88ba)
![2024-01-23_03 27 59](https://github.com/Apollounknowndev/tectonic/assets/6725027/4a737a1c-bed0-48ef-a38a-c97b145b6068)

However, on fabric with the same mods this does not happen anymore. Instead, the deep ocean sometimes generates dirt/grass at the surface, but underwater structures spawn at the depth they should be and icebergs do as well but underground is broken. (also only when generating adjacent to a mushroom biome.) This has been a thing since forever (1.18). I just stopped using terralith because river tunnels are dope. 
![noterra](https://github.com/Apollounknowndev/tectonic/assets/6725027/f0fae2ad-b07b-4ad1-ab70-a56db47ecbdc)
![2024-01-21_20 33 20](https://github.com/Apollounknowndev/tectonic/assets/6725027/5dd8a1e4-5905-4ba0-9494-6be01cc8b1c6)

Doesn't happen with/out terralith and all other variables, doesn't happen with tectonic with all other variables. (but the first instance can with just tectonic) So I initially thought terralith was the issue... then through a lot of comparing generation on multiple versions of a test seed, I also noticed that wilder wilds was generating underground features I hadn't noticed before... but only without tectonic. why just mushroom biomes and deep oceans? lol everything else is nearly perfect.

I've documented the process/modlist/etc on the terralith discord and am active if anyone has questions about specifics.

Whether or not fixes are possible, any suggestions for a workaround are welcome.

**Comment by Apollounknowndev** [comment]
Which Tectonic version are you using?

**Comment by grugsy** [comment]
2.2

**Comment by grugsy** [comment]
The more I look at the open issues and look at what's happening in-game, the more I think it's all related to biome blending, or lack thereof in about 1/3 of them. this sunken biome issue, the weird behavior near water, the buggy cliffs. all share one thing in common, hardline breaks in between land and water biomes with no transition/blending. 
![2024-01-29_01 49 50](https://github.com/Apollounknowndev/tectonic/assets/6725027/96638c4f-c691-4c21-9cfc-67ed030ba5d1)
![2024-01-29_01 51 39](https://github.com/Apollounknowndev/tectonic/assets/6725027/325cc741-9fc2-455d-8cb3-b963b9864f93)

**Comment by grugsy** [comment]
now that I'm looking for that, comparing maps, it's always transitions in elevation between biomes. (rivers included in some cases) very obvious on this one... one of the worst cases I've seen. 
![nogrid](https://github.com/Apollounknowndev/tectonic/assets/6725027/55608bd5-2ddf-406c-86b7-1b4466a9414f)

**Comment by grugsy** [comment]
I had a breakthrough.. I get it now... freaking terrablender.
![How-Terrablender-works-with-BYG](https://github.com/Apollounknowndev/tectonic/assets/6725027/b7f7b596-7699-401f-b2f0-65fd4d79dbad)

**Comment by grugsy** [comment]
I know what's happening now. It's not at all an issue on your end or a terrablender issue in this case. It's other biome mods that use terrablender replacing a mushroom biome with another biome type entirely. in the instance that your mod or terralith changes the depth of the surface of a biome in that spot, the parameters don't match so terrablender defaults to ocean and flattens.
