### ISSUE TITLE
Terrain generating almost exactly the same in every World

### ISSUE THREAD

**Issue by MageOfGaming** [Apollounknowndev/tectonic#92]
When generating a world in v2.2 it generates the exact same world as it would if you would generate a different world, the terrain is the same and biome distribution always the same by the factor of climate, in my case there is always a river a few blocks north from the spawn that always goes into a cave

**Here is a screenshot:**
![tectonic worldgen issue](https://github.com/Apollounknowndev/tectonic/assets/143808191/9ab9826c-e7a9-4054-b442-d08ca6b0d371)

**Comment by NolanHewitt** [comment]
Does it generate like that even when you switch it to superflat?

**Comment by Apollounknowndev** [comment]
Duplicate of #84, fixed in v2.2.1.
