### ISSUE TITLE
Alex's Caves Abyssall Chasm Does not Generate Sometimes With V2.2

### ISSUE THREAD

**Issue by SanguineWaters** [Apollounknowndev/tectonic#95]
### Describe the Bug
The Abyssal Chasm from Alex's Caves more often than not (From my limited testing), does not generate but leaves the structures meant for the biome spawning on the sea floor which happens when a certain Y level is met for Alex's Caves in which the structures will spawn. All other cave biomes are fine from what I have seen with the lava rivers running through some which is cool and fine.
### To Reproduce
Use Abyssal Chasm Map
Find the Chasm and get lucky or unlucky

### Relevant Files
alexscaves-1.0.9
aquamirae-6.API15 (Adds a new icy maze structure/biome area with some structures and a boss fight)
BiomesOPlenty-1.20.1-18.0.0.598
RegionsUnexploredForge-0.5.3.1+1.20.1
tectonic-mod-1.19.3-v2.2
TerraBlender-forge-1.20.1-3.0.1.2
Forge 1.20.1-47.2.20

![2024-02-13_00 30 21](https://github.com/Apollounknowndev/tectonic/assets/159096108/dc0d58b8-2216-446b-b949-64f4381f227b)
![2024-02-13_00 30 43](https://github.com/Apollounknowndev/tectonic/assets/159096108/eff55ece-4e1f-494b-8390-016baa5e09c7)
Instance where the biome generated well with some structures still spawning out of the original biome due to the low Y level of the seafloor.
![2024-02-13_21 28 29](https://github.com/Apollounknowndev/tectonic/assets/159096108/d33bb726-b82b-4fe7-adfe-bf471f93f255)
An instance where you see the coral reef biome stops generating where an Abyssal Chasm is supposed to generate.
![2024-02-13_21 55 10](https://github.com/Apollounknowndev/tectonic/assets/159096108/00a97521-dd60-41c0-bdd5-10876b5050da)
![2024-02-13_21 55 05](https://github.com/Apollounknowndev/tectonic/assets/159096108/c163e990-de15-4dbf-b795-c7de18e203d6)

[Mod.list (2).txt](https://github.com/Apollounknowndev/tectonic/files/14275010/Mod.list.2.txt)

**Comment by Apollounknowndev** [comment]
This cannot be fixed. The developers of Alex's Caves are simply marking mods that increase ocean depth as incompatible.

**Comment by SanguineWaters** [comment]
Thank you for the reply. It sucks that it is incompatible but that's life.

**Comment by SanguineWaters** [comment]
With some quick testing, it seems like I have found a fix in which it will generate the biome more often, but it is not perfect. The abyssal chasm map will be semi-inaccurate, some of the structures will spawn outside of the abyssal chasm on the regular ocean floor, and terrain and structure placement in the biome is not perfect, however I am more than happy it will generate more often. The way to fix is is to change the depth config to be lower.

Steps:
%appdata%
.minectraft -> config -> alexscaves_biome_generation -> abyssal_chasm
Change to the config below
  "depth": [
    0.1,
    1.2
Do some testing to to fit your needs or improve it, this was a random first try for me.

**Comment by Vinzound** [comment]
> With some quick testing, it seems like I have found a fix in which it will generate the biome more often, but it is not perfect. The abyssal chasm map will be semi-inaccurate, some of the structures will spawn outside of the abyssal chasm on the regular ocean floor, and terrain and structure placement in the biome is not perfect, however I am more than happy it will generate more often. The way to fix is is to change the depth config to be lower.
> 
> Steps: %appdata% .minectraft -> config -> alexscaves_biome_generation -> abyssal_chasm Change to the config below "depth": [ 0.1, 1.2 Do some testing to to fit your needs or improve it, this was a random first try for me.

Thank you very much, I also have that problem and this will help me too.

Maybe this problem can be overcome directly by the creator of Alex's Caves, I'm not sure.

**Comment by Apollounknowndev** [comment]
Setting `deeper_oceans` to `false` in the Tectonic mod config should also fix the issue

**Comment by Leviathanize** [comment]
> Setting `deeper_oceans` to `false` in the Tectonic mod config should also fix the issue

Sorry to drag up this old issue. but using the Tectonic-3.0.19 Neoforge, I am unable to find the "deeper_oceans" in the config file for Tectonic. could you please clarify where it's suppose to be?

**Comment by Apollounknowndev** [comment]
Now this would be setting `ocean_depth` to -0.12 and `deep_ocean_depth` to -0.22.
