### ISSUE TITLE
Is there any way to config any thing?

### ISSUE THREAD

**Issue by Shadowyjp** [Apollounknowndev/tectonic#97]
Biomes sizes, biomes heights etc

**Comment by Apollounknowndev** [comment]
Not without manually editing the files, no.

**Comment by ErrorPower2001** [comment]
If the game has already started(main menu or in a world) and I edit the configuration, do I have to restart the game for the editing to take effect?

**Comment by Apollounknowndev** [comment]
Yes, a restart is required
