### ISSUE TITLE
Large Biomes Not Working

### ISSUE THREAD

**Issue by SamMcClatchey** [Apollounknowndev/tectonic#99]
I remember using this mod a while ago and large biomes working and it seems to have been made compatible with the world type in v2.1 but I'm currently using v2.2 and the large biome world type does not affect world gen when used with tectonic. I tried both the datapack and mod versions and I'm using Fabric 0.15.7 got mc 1.20.4.

**Comment by MageOfGaming** [comment]
> I remember using this mod a while ago and large biomes working and it seems to have been made compatible with the world type in v2.1 but I'm currently using v2.2 and the large biome world type does not affect world gen when used with tectonic. I tried both the datapack and mod versions and I'm using Fabric 0.15.7 got mc 1.20.4.

I think you can set biome sizes in the datapack

**Comment by Apollounknowndev** [comment]
Fixed in v2.2.1.
